### ISSUE TITLE
Troll Heal Bug

### ISSUE THREAD

**Issue by L33t-HAXXOR** [Gelbpunkt/IdleRPG#102]
**Description**
Whilst participating in an active adventure, the enemy and I can effectively spend hours healing ourselves. We can even restore HP _beyond_ our initial starting HP. This gets old _real_ quick. 

**To Reproduce**
1. Start `activeadventure`
2. Heal yourself ad infinitum
3. Alternatively, watch the enemy heal itself ad infinitum

**Expected behavior**
Each rival should be able to heal only up to their initial maximum HP [e.g. 100/100]
Attack damage value should be greater than HP restoration value by a degree of ten or more. [e.g. RST base 20, ATK base 30]
Alternatively, you can preserve the current values but limit the number of heals via comestibles [e.g. potions/stimpaks] 

**Screenshots**
Screenshots can be provided upon request.

**Desktop (please complete the following information):**
 - OS: 
 - Browser 
 - Version 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by Gelbpunkt** [comment]
Added for active battles and adventures.
