### ISSUE TITLE
Errors while installing

### ISSUE THREAD

**Issue by D3rise** [Gelbpunkt/IdleRPG#103]
**Describe the bug**
While `setup.sh` executing, I get an error with `psql`, with `git` while dependencies install and with `sed`

**To Reproduce**
1. Enter console command `setup.sh`

**Expected behavior**
A clear installation without errors

**Screenshots**
![error screenshot](https://i.imgur.com/63Usl2g.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Server
 - Version 18.04.2
- Python 3.6.8
- PostgreSQL 10.9 (Ubuntu 10.9-0ubuntu0.18.04.1)
- Bash 4.4.20
- IdleRPG bot source v3.6

**Comment by Gelbpunkt** [comment]
As it says, you have to configure Postgres before running the script. We cannot provide individual support with selfhosting the bot, as the code should be self-explanatory and we assume you to be able to setup an environment for deployment your own when attempting to do so. Cheers
