### ISSUE TITLE
$t for timers

### ISSUE THREAD

**Issue by AutobotJazzy** [Gelbpunkt/IdleRPG#105]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Was wondering if like $s for status and $p for profile, there could be a $t for timers?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Defenestrate-flof** [comment]
If we gonna make shortcuts for $timers, can $activate and $guild have one too?
Like $activate time/1/t and $guild/g invest.

**Comment by Gelbpunkt** [comment]
Added the main issue's suggestion in v4
