### ISSUE TITLE
Why can you $Merge an armour with a sword?

### ISSUE THREAD

**Issue by forceeeee** [Gelbpunkt/IdleRPG#108]
**Is your feature request related to a problem? Please describe.**
I merged a piece of armour with a sword thinking it would work, but it did! I don't know if this
was intended or not.

**Describe the solution you'd like**
People may not agree with me but, make it so that you can merge ***only*** with it's same type.

**Describe alternatives you've considered**
It may be hard for the Idle-Bot to know if said item is an armour peice or not, so maybe add a
Different ID code system for armour pieces .

**Additional context**
An example of an alternative is maybe using letters e.g. A2033921 to indicate said item is a peice of armour, and S48402839 for swords, and if the Bot detects an "A" **AND** an "S" in the ID code,
The bot tells you that you can't do that, and that to be able to Merge, it would need 2 "A"'s or 2 "S"'s
For the $Merge to work. Sorry if you diddin't understand :P

**Comment by forceeeee** [comment]
I can explain it to you better if you dont understand @Gelbpunkt

**Comment by Gelbpunkt** [comment]
This would be extremely easy to add, but I'll leave it for discussion as it's a breaking change.

**Comment by Gelbpunkt** [comment]
Added in v4

**Comment by forceeeee** [comment]
:D
