### ISSUE TITLE
guild adventure cooldown on failed attempt

### ISSUE THREAD

**Issue by blitzvergnugen** [Gelbpunkt/IdleRPG#111]
**Describe the bug**
If a guild adventure has been completed, but the 'guild status' command has not been issued, then attempting to start a guild adventure will failed and trigger a cooldown.

**To Reproduce**
1. Start a guild adventure with '$guild adventure'
2. Complete adventure
3. Issue '$guild adventure' command
4. Message "Your guild is already on an adventure! Use `$guild status` to view how long it still lasts." should appear.
5. Recognize adventure completion with '$guild status'
6. Attempt to start new guild adventure with '$guild adventure'
7. Message "You are on cooldown. Try again in 0:59:54." will appear (exact time will vary).

**Expected behavior**
'$guild adventure' should start a new adventure as long as one is not currently in progress.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 75.0.3770.80

**Comment by blitzvergnugen** [comment]
Ideally, '$guild adventure' should recognize the completion of the adventure and start a new one. I think just resetting the cooldown if the adventure is complete would be sufficient. 

I believe modifying the adventure function in guild.py with the code below would suffice.
```
async def adventure(self, ctx):
        _("""Starts a guild adventure.""")
        adventure = await self.bot.get_guild_adventure(ctx.character_data["guild"])
        
        if adventure:
            if adventure[2]:
                await self.bot.reset_cooldown(ctx)
```

Stretch goal would be to function-ize the contents of `if adventure[2]:` in `status()` and process completion with '$guild adventure'

Honestly, I'd submit a pull request myself, but not looking to setup a test platform.

**Comment by Gelbpunkt** [comment]
This should be fixed in v4
