### ISSUE TITLE
Command to disable/enable bot's permissions

### ISSUE THREAD

**Issue by Defenestrate-flof** [Gelbpunkt/IdleRPG#117]
**Is your feature request related to a problem? Please describe.**
Setting up bot permissions for channels is really time-consuming, especially for huge servers.

**Describe the solution you'd like**
A command that can disable/enable the bot’s permissions to post in a channel. It can either be like Coffee bot, asked for permissions after you open a new channel; or like Pokecord, with a separate command that can be used manually. [I hope this isn't illegal]

**Describe alternatives you've considered**
It would be twice the spice if both features get implemented. However, if we can only get one out of the two it would already be nice enough.

**Additional context**
I can’t find the channel command code on Pokecord’s Github so I’ll send in a pic.
![image0](https://user-images.githubusercontent.com/52734271/62722334-68c22680-ba38-11e9-98eb-6f9581e64264.png)

**Comment by Gelbpunkt** [comment]
This would affect the bot speed as it would be checking against a list of enabled channels and that's the reason why I tell people to use Discord permissions. They don't slow my bot down and are easier to control.

**Comment by Defenestrate-flof** [comment]
So that's why, thank you for the info fam.
