### ISSUE TITLE
Provide sql schema in source?

### ISSUE THREAD

**Issue by gimmic** [Gelbpunkt/IdleRPG#12]
I was hoping to stand up a dev environment but I'm not seeing the sql schema defined anywhere.

Would it be possible to have a setup function included to build the db or otherwise provide a schema?

**Comment by Gelbpunkt** [comment]
I thought we included it, huh. How do you plan to use the code? Why do you need the scheme?

**Comment by gimmic** [comment]
Well, I'm trying to stand up a dev instance.. it doesn't work very well without the backend DB!
I'm hoping to experiment with dynamic changes to content in messages based on the emote responses and generally play with service improvement. Honestly, it's a good excuse to practice python for me.

It might be nice to have a bare-bones database available to import included in the source to make a test environment functional. You don't even have to include all the content.. maybe just some basic placeholder data.

**Comment by Gelbpunkt** [comment]
I think it's best to release the scheme when I changed the license to our final intention, which might take a few days. I'll discuss it with Mary asap!

**Comment by gimmic** [comment]
Just a ping on this. Thanks!

**Comment by Gelbpunkt** [comment]
Now that licensing is clarified, I will publish the scheme in the next days (when I got time). Thanks for the issue!

**Comment by Gelbpunkt** [comment]
@gimmic done, although maybe a bit late
