### ISSUE TITLE
Attack feature

### ISSUE THREAD

**Issue by LoliHubFTW** [Gelbpunkt/IdleRPG#124]
**Additional context**
Random Attack feature.

"$attack  1000 random"
(bot finds another player on the same server with the closest stats and forces an attack.)
Cooldown 1 hour? (so people don't abuse it)

**Comment by Gelbpunkt** [comment]
Not gonna do this, sorry. Also, your description makes no sense. Attack? What? Which effect? What happens?
Please follow the format
