### ISSUE TITLE
Stat cap

### ISSUE THREAD

**Issue by forceeeee** [Gelbpunkt/IdleRPG#125]
**Is your feature**~~request related to a problem?~~  **Please describe.**
Make it so you have a maximum stat you can equip according to your level. This is to make it so that rich people can still donate to noobs, but they can't have 20-20 all of the sudden and breeze through the first levels.

**Describe the solution you'd like**
Level:   Max stat:
   1••••••••••••••5
   2••••••••••••••9
   3•••••••••••••12
   4•••••••••••••15
    5••••••••••••19
    6••••••••••••22
    7••••••••••••25
    8••••••••••••30
    9••••••••••••35
   10••••••••••40
   11••••••••••41+
    
     

**Describe alternatives you've considered**
You can alter the level/stat if you think it's inaccurate

**Additional context**
~~i'm jealous of all the gifted level 1s that go to high adventure levels so quickly and I had to learn it the hard way and suffer the deaths D:~~

**Comment by Gelbpunkt** [comment]
They have to go on adventure 1 anyways due to the level lock. If they want to loose the fun of advancing in the game, tbh, it's not our problem

**Comment by forceeeee** [comment]
Just an idea :D

**Comment by forceeeee** [comment]
You r shooting down my suggestions 1 by 1

**Comment by Gelbpunkt** [comment]
Read my comment ^^

**Comment by forceeeee** [comment]
I did ;)
