### ISSUE TITLE
Item bonuses

### ISSUE THREAD

**Issue by forceeeee** [Gelbpunkt/IdleRPG#126]
**Is your feature** ~~request related to a problem?~~ **Please describe.**
it would be nice if there was stat bonuses depending to the weapon you have.

**Describe the solution you'd like**
Make it so if you are a ranger, and the weapon your using is a bow, then your pet has higher chance of finding a good item, or you have +1 dmg. Or if you are theif and your weapon is a dagger you have a higher chance of your $steal being sucsessful, or +1 dmg

**Describe alternatives you've considered**
For mages you get +1 def if you have a wand. And if you have a sword you get +1 dmg if you have a sword and your a warrior

**Additional context**

~~if you give me a cool role on idle I will think of features every day~~

**Comment by Gelbpunkt** [comment]
This is nothing for IdleRPG and already planned in Travitia
