### ISSUE TITLE
Beta Rangers cant view pet

### ISSUE THREAD

**Issue by Defenestrate-flof** [Gelbpunkt/IdleRPG#127]
**Describe the bug**
beta pet doesn’t work for some Rangers, Bowman in this case

**To Reproduce**
1. Ask Nothing#7745 (503628641981300746) or Nanashi#7404 (451934676706263043) to do beta pet

**Expected behavior**
Pet menu should shows up

**Screenshots**
https://imgur.com/a/HoDAY62

**Smartphone (please complete the following information):**
 - Device: iPhone 7 Plus
 - OS: iOS.12.4
 - Browser: Discord application 
 - Version: 3.1.0

**Additional context**
None

**Comment by Gelbpunkt** [comment]
Not a bug. They have to rechoose Ranger because the pet gets added when you select the class
