### ISSUE TITLE
Problem with the pet update

### ISSUE THREAD

**Issue by maxx0911** [Gelbpunkt/IdleRPG#128]
**Is your feature request related to a problem? Please describe.**
The pet values, especially love, decrease *way* too fast. I assigned the ranger class at roughly 5pm yesterday and tried what the `pet cuddle` command does. Obviously couldn't use that command before I went to bed, so I just left the pet as is, food, drinks and joy at almost 100, love at 90. Woke up today at 7am to a message saying my pet ran away.

Edit: the issue actually lies [here](https://github.com/Gelbpunkt/IdleRPG/blob/v4/utils/checks.py#L301). If I read that right, your pet can run away if the love is at 98 and random chance goes against you? That should be changed instead.

**Describe the solution you'd like**
It would be best if the decrease of those points would be cut in half or otherwise reduced, since I can't be on Discord precisely every 12h to use the pet commands.

**Describe alternatives you've considered**
One alternative is to raise the maximum of points from 100 to 200 or even more. Another option is to shorten the cooldown time for `pet cuddle`, and `pet play` (if that one has a cooldown too.)

**Additional context**
None

**Comment by maxx0911** [comment]
Should probably also add that `secrets.randbelow(12) + 1` is not enough points to add if the decrease is more than 1 point per 2 hours.

**Comment by numbermaniac** [comment]
Perhaps there should be a threshold that must be reached before the pet can run away. For example, making the pet only able to run away if love is less than 50.

**Comment by Gelbpunkt** [comment]
It'll run away on lower than 75% only now. Cuddle cooldown is 6h now
