### ISSUE TITLE
Double or steal minigame

### ISSUE THREAD

**Issue by forceeeee** [Gelbpunkt/IdleRPG#131]
**Is your feature request related to a problem? Please describe.**
It would be cool if you can add a ***Double or steal*** minigame to idlerpg.

**Describe the solution you'd like**
You do a command like. $dos (double or steal) @player.you start with 100 coins. You chose to double it or steal it. Say you chose double. It's other person turn. He can double 200 to make it 400 or he can steal it all. This game would keep going on untill one chooses to steal. And all the money automatically goes to the stealer

**Describe alternatives you've considered**
You can make the double or steal things into react emojis and uhh yea that's all I got to say

**Additional context**
This minigame  is a balance between Greed and trust.

**Comment by Gelbpunkt** [comment]
I actually do like this idea and will add it for v4

**Comment by forceeeee** [comment]
~~For the first time in foreverrr~~

**Comment by maxx0911** [comment]
Might also make it a group minigame where you can join with reactions, similar to Hungergames. I would suggest that the one that's chosen to double or steal is in a set order.

**Comment by forceeeee** [comment]
Cool idea. Like if you want a group, do $dos. If you want a 1v1, do $dos 150 @player

**Comment by Gelbpunkt** [comment]
Added with $100 starting money
