### ISSUE TITLE
$fe Survival rate

### ISSUE THREAD

**Issue by itsDoodlez** [Gelbpunkt/IdleRPG#133]
The problem right now with the 7/8 chance of growing and the remaining 1/8 chance of dying is that the chance of growing is too low. I’ve had 3 of my kids dying in a row at the age of two and I have yet to get a child to its teenage years (17% chance). Having child to even reach its adult years sounds like a far off dream (6% chance).

Please do increase the survival rate to more than just 7/8 I don’t wanna see my kids dying so often.

Using actual statistics from 2001 and calculating from there, the % chance of surviving every year before 65 years old is pretty high:
![01111EC9-7EB2-45C4-AD01-1A766DB74A2E](https://user-images.githubusercontent.com/54069642/63029738-a7962780-bee3-11e9-812a-b625c6e63bba.jpeg)

**Comment by Gelbpunkt** [comment]
Do you have an alternative suggestion to the death rate?

**Comment by forceeeee** [comment]
I would say that **-<5%** would be good.

**Comment by Gelbpunkt** [comment]
29/30 makes a chance of 54.3% to get 18 years, which sounds fair.

It doesn't have to be realistic, to be honest.

**Comment by Gelbpunkt** [comment]
Feedback wanted so I can close this

**Comment by blitzvergnugen** [comment]
I'm not sure the percentages matter until there's a reward system for getting kids to a certain age.
