### ISSUE TITLE
Beta Active Adventure Treasure Tile Bug

### ISSUE THREAD

**Issue by Nanashi7404** [Gelbpunkt/IdleRPG#134]
**Describe the bug**
Beta activeadventure glitches when you reach a tile with treasure. 
**To Reproduce**
1. Do 'Make your character reach a treasure tile '
2. Enter command 'beta activeadventure'

**Expected behavior**
Whenever a character reaches a treasure tile this message is sent by the bot "The command you tried to use ran into an error. The incident has been reported and the team will work hard to fix the issue!"
**Screenshots**
![Screenshot_20190814-220558_Discord](https://user-images.githubusercontent.com/54116487/63042419-64d44f80-bee3-11e9-9104-1b97c3827e59.jpg)

**Comment by Gelbpunkt** [comment]
Fixed a while ago
