### ISSUE TITLE
Upgrade attempt cooldown

### ISSUE THREAD

**Issue by NotWorthMyTime** [Gelbpunkt/IdleRPG#136]
I would love to see, that the actual cooldown only drains if the user does an upgrade, not when the command is sent.
If one guy does $upgrade, the attempt is drained and the cooldown hits, so the user has to wait one hour to do the actual upgrade. That should be removed and the cooldown should only takes effect, when the upgrade is actually done.

**Comment by Gelbpunkt** [comment]
Fixed by @numbermaniac
