### ISSUE TITLE
Lending feauture

### ISSUE THREAD

**Issue by forceeeee** [Gelbpunkt/IdleRPG#141]
**Is your feature request related to a problem? Please describe.**
With the new trading system in v4.0, it would be nice to have a lending feature to lend friends and players items,

**Describe the solution you'd like**
It would be something like $lend [ID] [Price] [time] [@player] 

**Describe alternatives you've considered**
An example is $lend 6110284 1000 2h @Gelbpunkt 

**Additional context**
Maybe you can implement it within the actual trading system. Like there is a reaction for lending or trading.

**Comment by Gelbpunkt** [comment]
I don't think anyone would use this, also it'd require a new background task which I'm against
