### ISSUE TITLE
Mass merge

### ISSUE THREAD

**Issue by forceeeee** [Gelbpunkt/IdleRPG#143]
**Is your feature request related to a problem? Please describe.**
It would be nice to have something other than merching to get rid of your 10+ page of items laying around.

**Describe the solution you'd like**
It would be cool if you can *Mass merge*. you can put any stat with no limitations and merge them all together to get a chance of getting a good item. E.g a 15 stat 21 stat 12 stat 10 stat 19 stat combined together to get a chance of getting like a 31 stat

**Describe alternatives you've considered**
A *code structure* of it would be something like: $forge [id] [id] [id] [id] [id]
only 5 items max. And the bot will tell you if the forge was a success or not. If it is a sucsess,
You get a good item. The higher stats you put in, the higher chance of getting a good item.
the good item is the average between the numbers times 2 e.g. average of 15,21,12,10,19
Is 15.4, 15.4 x2 ~31 (rounded to the nearest whole Number)

**Additional context**
The chance of it working could be the percentage of the average, e.g the example above shows that the average is 15.4, so the chance of it being sucsessful is 15.4%. If that chance is too high. Then it could be the average divided by 1.5. So 15.4 ÷1.5 ~ 10%

**Comment by forceeeee** [comment]
But there is an overall stat limit so you can't go over and have chances of getting a 42+

**Comment by forceeeee** [comment]
E.g you can't put 5 30 stats and expect to get a stat 60 lol

**Comment by Gelbpunkt** [comment]
This is not the goal of merging. There's a reason why the command has a cooldown

**Comment by forceeeee** [comment]
If I were to put mass forging this would be added to v4.0
