### ISSUE TITLE
Suggestion: Adventure Cancellation Confirmation Message

### ISSUE THREAD

**Issue by anxxero** [Gelbpunkt/IdleRPG#145]
**Is your feature request related to a problem? Please describe.**
I accidentally cancelled a level 11 adventure which was 10 minutes from completing thinking the command was universal (I'm not sure how to describe it).  I was curious about the battle command but didn't want to initiate anything and instinctively typed $cancel and ended up sabotaging my mission.  I forgot that idling caused most things to cancel themselves.

**Describe the solution you'd like**
A confirmation message asking something along the lines of "Are you sure you want to cancel your adventure?  y/n".

**Describe alternatives you've considered**
Just something similar to confirmation messages when you attempt to sell equipped gear.

**Additional context**
n/a

**Comment by numbermaniac** [comment]
Fixed in v4 via #154
