### ISSUE TITLE
Me vs Me in tournament 

### ISSUE THREAD

**Issue by Nanashi7404** [Gelbpunkt/IdleRPG#146]
**Describe the bug**
I joined a tournament that had 4 entires. I won first match and second match. I should've won the tournament then but the bot made me fight myself which I won and then the tournament ended.

**To Reproduce**
1. Do 'start a tournament with 4 entires'
2. Enter command '$tournament 100'
3. Search for "What??" by Nanashi#7404 in channel Playground in official idleRPG server and scroll up to view tournament. 

**Expected behavior**
Tournament should end after I won two times straight in case of 4 entires. 

**Screenshots**
![Screenshot_20190818-213102_Discord](https://user-images.githubusercontent.com/54116487/63227577-4763f600-c201-11e9-901f-fd19a99838d1.jpg)

**Comment by Nanashi7404** [comment]
Update: 
In order for the bug to appear, you repeatedly react with sword emoji and the you get two entries into the tournament 

@Gelbpunkt

**Comment by Gelbpunkt** [comment]
Hmm the code is made so this shouldn't be possible

**Comment by Gelbpunkt** [comment]
Should be fixed
