### ISSUE TITLE
Beta Class First Choice bug

### ISSUE THREAD

**Issue by Nanashi7404** [Gelbpunkt/IdleRPG#150]
**Describe the bug**
When someone creates beta character and tries to choose class they cannot. The bot tells them that they are too poor. First choice was free before. They can choose class only if they have $5000. 

**To Reproduce**
1. Do 'Create a new beta character and try to choose class'
2. Enter command $class'

**Expected behavior**
First choice should be free as a new player cannot get 5k unless someone gives them the money. 

**Screenshots**
Can provide them if needed. Just ping me on discord @ Nanashi#7404. 
Don't want to mess up my beta profile. It is even better than my main 😁 But I can if you need SS. Or ask someone to make them instead.

**Comment by Gelbpunkt** [comment]
Should be fixed.
