### ISSUE TITLE
Scrolling through dungeons

### ISSUE THREAD

**Issue by 1InnocentKiller** [Gelbpunkt/IdleRPG#151]
Sometimes,when scrolling through levels in $dungeons using the normal arrow, it instantly takes me to the details of level 20,where I have to scroll back all the way to the wanted level details. 
**To Reproduce**
1. $dungeons 
2.  Right arrow. 

**Expected behavior**
To quickly reach the wanted details about the target level, and not instantly blink to lever 20.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Hawaii P30
 - OS:Idk what this is. 
 - Browser:I use the discord app and not any browser, but I use Chrome. 
 - Version of what? 

**Additional context**
It triggers me.

**Comment by Gelbpunkt** [comment]
Cannot repro. Please provide a video where this happens

**Comment by numbermaniac** [comment]
Is it possible you're clicking through the reactions too fast and accidentally clicking on the >> reaction at some point instead of the single arrow > reaction?

**Comment by Gelbpunkt** [comment]
Closing due to no feedback
