### ISSUE TITLE
Companionship VS Marriage

### ISSUE THREAD

**Issue by shintarowo** [Gelbpunkt/IdleRPG#153]
**Is your feature request related to a problem? Please describe.**
To add a companionship for those who would see it awkward to be married to someone or each other with the same benefits of being married.

**Describe the solution you'd like**
Add a buddy system that a person can have one companion or marriage so those who are not wanting to marry could get the same benefits.

**Describe alternatives you've considered**
Change Marriage slot to Companion/Marriage slot.

**Additional context**
submitting on behalf of *ODST J Sechemet#6100*

**Comment by Gelbpunkt** [comment]
To be honest, this would require adding two versions of wording everything, which this isn't worth to me. If you want the benefits of a marriage, then marry! 😄
