### ISSUE TITLE
beta pet commonds aren't working

### ISSUE THREAD

**Issue by AngelEden** [Gelbpunkt/IdleRPG#155]
**Describe the bug**
For the last few days I've been doing beta pet and the other beta pet commands. Nothing has been happening. The beta pet hunt doesn't give anything but will start the timer. Not sure how it can be fixed but wished to inform you of this current issue. Along with the option of doing your own pet image. It does not work. Option to help with that issue is to put if it needs to be png or jpeg along with a set size.

**Comment by Gelbpunkt** [comment]
The issue here is that your pet died and I wasn't properly resetting your class. You should re-choose Ranger to get a new pet

**Comment by AngelEden** [comment]
I only got to take care of it a bit... for like a day then it stopped working. *shrug* Can they die over night while your asleep? If so then the kill rate is high.
