### ISSUE TITLE
Duplicate Child Names

### ISSUE THREAD

**Issue by Chankster** [Gelbpunkt/IdleRPG#156]
**Describe the bug**
A collision of a $familyevent renaming event and a $child event can result in two children with the same name.

**To Reproduce**
1. Do $familyevent and then immediately do a $child
2. The $familyevent should result in a renaming option and the $child event should be successful
3. Pick a [name]
4. You will receive a "[name] was born" and an "[oldname] is now called [name]"
5. $family will show two children with the same name.  A death event will cause both to die.

**Expected behavior**
Only one action should happen at a time and prevent two children with the same name

**Screenshots**
https://imgur.com/a/59oCb32

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 76.0.3809.100

**Comment by Gelbpunkt** [comment]
Not sure if I wanna fix this behaviour. I don't mind it at all

**Comment by blitzvergnugen** [comment]
Easiest fix is to add age to the WHERE clause. Then you don't have to worry preventing duplicated names. 

That said, I do enjoy the double death.. Just would prefer to see a msg for each child if that behavior is maintained.

**Comment by Gelbpunkt** [comment]
I've added the age clause
