### ISSUE TITLE
Merge System for Crates v4

### ISSUE THREAD

**Issue by Nanashi7404** [Gelbpunkt/IdleRPG#157]
**Is your feature request related to a problem? Please describe.**
Well with v4 coming tomorrow I thought about what would happen to the crates people already have. I asked in support and was told that they'll be void or made equal to common crates. 

**Describe the solution you'd like**
Please don't void the crates. Some people have collected/bought ridiculous numbers of crates. It would be like an eco reset for them and another eco reset so soon after the last one *might not be good for IdleRPG*.
Also if crates will become common crates, can we implement a system where we can merge a specific number of crates to get a single crate of next rarity? 

**Describe alternatives you've considered**
*None for now. Would love to hear ideas from community*

**Comment by Gelbpunkt** [comment]
Crates will turn into common crates
