### ISSUE TITLE
Fun God Ideas

### ISSUE THREAD

**Issue by leafbladie** [Gelbpunkt/IdleRPG#159]
So I think the new Gods feature is pretty cool, but my only issue with it is that many of the Gods are based on Gods worshipped in history, like Athena and Jesus. It'd be nice if Gods from other media were considered as well.

Maybe it'd be good to have a vote or something on suggestions for Gods from different media. To give more variety to the types of choices. I'd really love it if I could see Ultimate Madoka, Super Saiyan God Goku, or Eva Unit-01 be a God on the server, and I think a lot of people would find it fun too, to support a God from their favorite work.

**Comment by numbermaniac** [comment]
For what it's worth, each God is a real player in the IdleRPG support server. It was their choice to name themselves that, not the decision of the developers.

**Comment by Gelbpunkt** [comment]
@numbermaniac said everything I would've said.
