### ISSUE TITLE
Profile idea

### ISSUE THREAD

**Issue by AngelEden** [Gelbpunkt/IdleRPG#160]
**Is your feature request related to a problem? Please describe.**
This isn't to a problem but a suggestion. Showing race and god on the profile.

**Describe the solution you'd like**
Not sure where it should go but it would be nice to see my race and god on my profile. Maybe next to where class is on the profile.

**Comment by forceeeee** [comment]
I like this Idea. I found a spot on where to put the race, but I don't know where to put the god.
![IMG_20190825_225728](https://user-images.githubusercontent.com/53173499/63654191-3af51580-c78c-11e9-8026-82b037c3bcea.jpg)

**Comment by AngelEden** [comment]
Maybe in the middle of that line? Or under where the adventure is?

**Comment by Gelbpunkt** [comment]
The original creator of this image is inactive and we lost the PSD file for it. It's hard to update it for that reason.
We might make the line under money longer and put the text to the right where there's a bunch of space

**Comment by AngelEden** [comment]
Do you have the original images? I could sit down with my Photoshop and see if I can work something.

**Comment by Gelbpunkt** [comment]
I'll try doing it my own this week :) shouldn't be too hard

**Comment by forceeeee** [comment]
I was thinking of making the god you follow a symbol, just like the class symbols at the bottom right.

**Comment by forceeeee** [comment]
I made an idea of where to put the god/race . It would be cool to have different symbols for each god so i put a symbol next to the god name, like to represent the god.
![IMG_20190826_114424](https://user-images.githubusercontent.com/53173499/63672602-87c20600-c7f7-11e9-87e8-4b1c4a3893ba.jpg)

**Comment by forceeeee** [comment]
And I don't know the fint for the personal writing so i chose random ones. Also I'm not an editor or anything so dont expect it to be good-looking. :D

**Comment by AngelEden** [comment]
I've been messing with my Photoshop with what I could find. Almost got the original remade last night. Once I get it done I'll share it. I think I have the original font on it as well.

**Comment by forceeeee** [comment]
I'd love to see it!

**Comment by AngelEden** [comment]
Not sure when you'll get this but I have the PSD file that I can send to you via DM's. But I hope this zip will help.
[Profile.zip](https://github.com/Gelbpunkt/IdleRPG/files/3595581/Profile.zip)

**Comment by Gelbpunkt** [comment]
With the new profiles, this is resolved
