### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Hanesor** [Gelbpunkt/IdleRPG#161]
**Describe the bug**

**To Reproduce**
1. Do 'Its one of the "$pet play" commands'
2. Enter command '$pet play'
3. Hit reaction '....'

**Expected behavior**
My gf was playing with her pet in IdleRPG and found a typo in the response, it should be ":rugby_football: but is sending :rugy_football: 

**Screenshots**
https://imgur.com/wKhRU4a.png

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Gelbpunkt** [comment]
Should be resolved.
