### ISSUE TITLE
Adventure percentages went down after update by a large amount

### ISSUE THREAD

**Issue by Nadaki10** [Gelbpunkt/IdleRPG#162]
Before the update my adventures were all over or close to being over 100% on the second percent and the first percent was generally between -80% and -28% but after the update I was going through my adventures and noticed that on adventure 18 Gambling Problems my lowest percent went from -62% to -201% and my highest went from 116% to 92% I don’t know if this is a bug or intentional but I don’t know how I’m supposed to be able to do them now I have included screenshots of before the update percentages on adventure 18 and after the update percentages on adventure 18. Thank you for your time.
![75E8FFD9-C8B7-49D4-A7FA-975C1CDF8282](https://user-images.githubusercontent.com/54489692/63644861-acaf5f80-c6b7-11e9-939b-bb029878a45d.jpeg)
![E60E4D58-02ED-4D95-A1AF-C0089E77FA60](https://user-images.githubusercontent.com/54489692/63644862-ad47f600-c6b7-11e9-816a-4d977b5e69fb.jpeg)

**Comment by Gelbpunkt** [comment]
Closing due to #204
