### ISSUE TITLE
Inform owner when pet runs away

### ISSUE THREAD

**Issue by maxx0911** [Gelbpunkt/IdleRPG#163]
**Is your feature request related to a problem? Please describe.**
Currently, when a pet runs away, you will not be notified, unless you check within the first two hours. After that, using any of the pet commands just won't output anything. I'd assume it goes the same for starving and the other ways to lose your pet too.

**Describe the solution you'd like**
Instead if setting the user's class to `None` when the pet runs away or dies, the class should be set to something like `Ranger..?` which will output the PetRanAway message when a pet command is used, and *then* change the class to `None`.

**Describe alternatives you've considered**
When the bot goes through the background task of updating the pets' values, when it detects that a pet died or ran away, it would direct message the pet owner.
Depending on how many users are rangers this might not be the best of ideas.

**Additional context**
[Screenshot of a confused user whose pet most likely ran off](https://cdn.discordapp.com/attachments/589132225610514615/615092909888372737/Screenshot_2019-08-25-09-58-58.png)

**Comment by Gelbpunkt** [comment]
Your pet chances to run away and starve are calculated once you use the first `$pet` command after a while. This means you *always* get a message saying it ran away or starved
