### ISSUE TITLE
Ranger repick

### ISSUE THREAD

**Issue by forceeeee** [Gelbpunkt/IdleRPG#164]
**Describe the bug**
We are all aware of the current bug where all the new rangers have to repick their second/primary class to ranger so they can use the commands. I'm a theif and chose ranger as a second class before the bug was known. I was told that I have to repick ranger. I waited another day to repick ranger again to ranger.
And I did $class, chose secondary class, and looked for ranger, There was no option to pick ranger.
So now the only way to get ranger is to change ranger into another class and then pick ranger again, which will cost 10k. And I'm not keen to spend 10k just because of a simple bug!

**How to Reproduce**
1. Be unaware of the bug
2. Chose ranger
3. Find out that there is a bug with the ranger and that you have to pay 10k to make it work.
4. Be mad
5. Make a github post about it.
6. It gets fixed???

**Expected behavior**
I expected for the class to be co-operative.  And respond to my commands.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [iPhone1]
 - OS: [OS. 3.1.3]
 - Browser [ http://xmh57jrzrnw6insl.onion/]
 - Version [6.9.0]

**Additional context**
"Fix this bug plz" - A triggered player.

**Comment by Gelbpunkt** [comment]
Secondary class ranger is ok, only primary class has the issue
