### ISSUE TITLE
Animal Race

### ISSUE THREAD

**Issue by PowerPotassium** [Gelbpunkt/IdleRPG#165]
No issues or anything, I was just hoping when races were first mentioned that there'd be a race of animal people, like the Warbeasts, a race of kemonomimis (people with animal ears (and tails I guess)).

Edit: Just saw the stat table for the races and it looks like every possibility of total stats of 4 is filled, but I do still want an animal race. Please consider!

**Comment by Gelbpunkt** [comment]
Not gonna add this, all possibilities that are within the 4 stat range are added and I don't plan to change it
