### ISSUE TITLE
Active adventure time-out

### ISSUE THREAD

**Issue by Sunshinegirl04x** [Gelbpunkt/IdleRPG#166]
**Describe the bug**
I was doing an active adventure, and in the middle of it, it randomly timed out. I’m sure it was not because I took too long, I didn’t go anywhere and reacted again within seconds after my last reaction. 
Maybe it was because idle lagged really hard, then thought I hadn’t reacted, and timed out because of that.

**Comment by Gelbpunkt** [comment]
You always have 30 seconds to react. If it times out, *only* for the reason of a real 30 seconds timeout, and not anything else.
https://github.com/Gelbpunkt/IdleRPG/blob/v4/cogs/adventure.py#L193
https://github.com/Gelbpunkt/IdleRPG/blob/v4/cogs/adventure.py#L288
https://github.com/Gelbpunkt/IdleRPG/blob/v4/cogs/adventure.py#L337
https://github.com/Gelbpunkt/IdleRPG/blob/v4/cogs/adventure.py#L342
