### ISSUE TITLE
Ranger Rebalance

### ISSUE THREAD

**Issue by Stevelion** [Gelbpunkt/IdleRPG#167]
**Is your feature request related to a problem? Please describe.**
Many people have been complaining that the upkeep for pets isn't worth the rewards

**Describe the solution you'd like**
Lower pet upkeep costs/rate

**Describe alternatives you've considered**
Raise hunt rewards to be similar to a rare crate at higher evolutions

**Comment by BioGeekJoey** [comment]
Agree. The love and joy stat seem to drain faster than what you can realistically refill using the pet cuddle and pet play command, given their cool down.

**Comment by Gelbpunkt** [comment]
Should be 10 times cheaper in v4.1
