### ISSUE TITLE
Exchanging loot for XP will not trigger the leveling up check

### ISSUE THREAD

**Issue by mmoftah** [Gelbpunkt/IdleRPG#170]
**Describe the bug**
This bug is that when using the exchange command on loot and receiving XP it is missing the check for leveling up. If the XP rewarded levels you up, you will not get the reward.

**To Reproduce**
1. Have an item with high enough value to level you up.
2. Enter command `exchange <item id>`
3. Hit the reaction that corresponds to the XP

**Expected behavior**
It is expected that you will receive your leveling up reward upon a successful level up.

**Comment by Gelbpunkt** [comment]
Fixed in v4.1
