### ISSUE TITLE
Raid website: "Raiders joined" counts up infinitely if nobody has joined yet

### ISSUE THREAD

**Issue by numbermaniac** [Gelbpunkt/IdleRPG#171]
**Describe the bug**
If I'm the first person to go to the raid website after a raid is spawned, the number of people who have joined the raid should be zero. However, on the website, the animation to show the number of people keeps ticking up forever. If it's 1 or above, it stops at the right number -- but if it's 0, it counts up forever.

**To Reproduce**
1. Spawn a raid.
2. Go to the raid website before anyone joins.
3. Notice that the "Raiders joined" keeps going up forever.

**Expected behavior**
It should just stop at 0.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: 68.0.2

**Additional context**
I don't know how it's implemented, but my guess it's probably a loop that starts at 1 and goes upwards until it reaches the right number. If the right number is 0, it's never going to get there because it's counting upwards from 1.

**Comment by Gelbpunkt** [comment]
Should be fixed
