### ISSUE TITLE
Unable to access $family command

### ISSUE THREAD

**Issue by Azaelo13** [Gelbpunkt/IdleRPG#173]
1.Do $fe until you get the chance to change child's name
2. Send a Image
![image](https://user-images.githubusercontent.com/54547504/63706351-7563be80-c82f-11e9-93d4-a77dcca95ad7.png)

**Comment by Gelbpunkt** [comment]
Good catch.
I can fix it, but I'll need your user ID to fix your child name

**Comment by Gelbpunkt** [comment]
should be fixed in v4.1
