### ISSUE TITLE
Ranger $pet hunt doesn't work

### ISSUE THREAD

**Issue by metalcupcake5** [Gelbpunkt/IdleRPG#174]
**Describe the bug**
When using `$pet hunt`, I get no response from the bot, the cooldown starts, and no item is put in my inventory.

**To Reproduce**
1. Pick the ranger class
2. Enter command `$pet hunt`

**Expected behavior**
I expect to have a embed sent from the bot and to have an item in my inventory.

**Screenshots**
![image](https://user-images.githubusercontent.com/43897385/63718632-d96e8e80-c7ff-11e9-8182-570359f7937d.png)

**Additional context**
This only started happening after the latest update(v4.0.0)

**Comment by Gelbpunkt** [comment]
Fixed
