### ISSUE TITLE
Booster for loot

### ISSUE THREAD

**Issue by shintarowo** [Gelbpunkt/IdleRPG#175]
**Is your feature request related to a problem? Please describe.**
would a booster that doubled the chance of getting loot from adventures be too good or is that a plausible request? 

**Describe the solution you'd like**
Make a Loot Booster that doubles the chance of getting loot
for the price of 1k
**Describe alternatives you've considered**

**Additional context**
Requesting this for an user since they ask so nicely.

**Comment by Gelbpunkt** [comment]
I wouldn't like this but can imagine making the chance 2/10 for ritualists
