### ISSUE TITLE
GUILD FEATURES

### ISSUE THREAD

**Issue by BrownIndianGuy** [Gelbpunkt/IdleRPG#179]
**Is your feature request related to a problem? Please describe.**
No 
Just a feature which needed

**Describe the solution you'd like**
Add perks for guilds so more join guilds

**Describe alternatives you've considered**

Add boosts in guild so more join guilds. Like

 Luck,time, money, atk, def etc... 
All can be upgraded by spending money from guild bank. All are permanent for a guild but you will loose the boost if you leave that guild.

Luck, time, money boost will increase 0.5% per level
Atk&def +1 evey level (costlier than boost). 

If you want you can add raid boost too

**Comment by Gelbpunkt** [comment]
I don't like this idea. Guilds should offer a community, not a way to become op

**Comment by BrownIndianGuy** [comment]
> I don't like this idea. Guilds should offer a community, not a way to become op

then any server can work as community no need for guilds
