### ISSUE TITLE
Loot Trading

### ISSUE THREAD

**Issue by hermes-motorad** [Gelbpunkt/IdleRPG#180]
**Feature Request**
Making loots available for trade. 

**Comment**
I'm sure there are people who would rather sell and buy loots since they are so rare, especially the ones with more value in it. To add, not all people would be invested or interested in the god systems. If loots would be available for trade, then that in itself would become a market of its own. A lot of work, but if it's plausible, then it would be great. Thanks :)

**Comment by Gelbpunkt** [comment]
I don't want people to buy high favor with gods
