### ISSUE TITLE
$Activate all to activate all 3 boosters

### ISSUE THREAD

**Issue by platium2017** [Gelbpunkt/IdleRPG#182]
**Is your feature request related to a problem? Please describe.**
It would be nice to activate all 3 boosters with one command (provided the user has all 3 available) and would also reduce the traffic between bot and user a tiny bit.

**Describe the solution you'd like**
Adding an "all" argument to the $Activate command to activate all three.

**Describe alternatives you've considered**
A nice alternative could be to have stackable booster timers, however i can think of reasons why you haven't chosen for that.

Thanks for your time and for the development of an awesome bot.

**Comment by Gelbpunkt** [comment]
added in v4.1
