### ISSUE TITLE
Raffle System for Raids

### ISSUE THREAD

**Issue by NotWorthMyTime** [Gelbpunkt/IdleRPG#183]
**Is your feature request related to a problem? Please describe.**
It is almost impossible to bid at the end of the raids, there is no reason to bet, when people just bidding over 600k and call it a day.

**Describe the solution you'd like**
A raffle system, where you can buy a max of 1 ticket, so everyone that survived has the chance to receive the loot. 

**Describe alternatives you've considered**
Any one knows the WoW loot system? An alternative would be this, so that x survived people throwing dices, with let's say 5-8 dices at once. If people get the same amount and no one is higher, they just repeat it. The highest dice will win.

If people are under the highest amount, they are out.

**Comment by Gelbpunkt** [comment]
If you want alternative loot distributions, take a look at god raids or ikhdosa raids. Zerekiel will stay auction-like
