### ISSUE TITLE
Bring back the god Seren

### ISSUE THREAD

**Issue by AngelEden** [Gelbpunkt/IdleRPG#188]
**Is your feature request related to a problem? Please describe.**
This is mainly a request to bring back Seren as a god. I originally did not pick this god because of the person but the description of the god. I know others, like myself, would like this back for the same reason.

**Describe the solution you'd like**
Pick another person to run the God.

**Describe alternatives you've considered**
Picking another God is a good idea but I for one did not want to and wished staff considered possibly having another run it. 

**Additional context**
I know it seems like I'm being possibly angry and mean. I'm not trying to be. Just wishing to bring up an alternative other than removing a full god that had many followers and making us reset our god. I for one do not like the other gods based on description (no offense to the staff that run them). Please consider this idea because it seems very unfair to players who have picked this god to just remove it and make us reset after we have been told it is final. Thank you for hearing me out.

**Comment by Gelbpunkt** [comment]
I think I speak for the whole staff if I say that we don't want to replace Seren, because none of us is like Seren or wants to take her place.

**Comment by Gelbpunkt** [comment]
A ban from the bot due to breaking the rules is permanent, she won't come back
