### ISSUE TITLE
Group adventures for gods

### ISSUE THREAD

**Issue by Slavis-from-Idle** [Gelbpunkt/IdleRPG#193]
**Is your feature request related to a problem? Please describe.**
No, it is just a proposition of sth new, loose proposition, probably overcomplicated

**Describe the solution you'd like**
I was wondering, what, if gods would have their own mini adventures, that will gain favor and / or loot (maybe also standard rewards, like exp / gold /items ). For example, followers of Athena could team up to try to follow the footsteps of Hercules and repeat his deeds. 
More, perhaps the effects of such adventures can be recoreded in some kind of leaderboard (in form of points), so for example followers of one deity as a whole could compete with these from other gods (like we have 3 followers with max favor agains these from other faiths).
The most important aspect of this would be how to make it (start of adventure) player based - to avoid putting more work on shoulders of gods. Perhaps a some kind of champion should be selected with right to do so? They would be selected for example by the god, based on favor, and will be reselected each week or sth.

**Describe alternatives you've considered**
Creation of guild type dedicated to service of god (like knightly order, a witch coven, monastery, brotherhood / sisterhood, some cult, etc.), that will allow to use guild mechanics, but in more purposeful way? In case of Athena it could be the Academia of <sth> or maybe Philosophers Circle or some Oracle cult?

**Additional context**
I was recently thinking about guild adventures, that, for me, are bringing little to the table (or perhaps Im do not see that clear enough). Gods adventures should be concentrated on bringing gods followers together on ground of service and praise of their deity.

**Comment by Gelbpunkt** [comment]
There are raids already for that and imo, i think that is enough
