### ISSUE TITLE
Add cooldown of $vote to $timers list

### ISSUE THREAD

**Issue by Nanashi7404** [Gelbpunkt/IdleRPG#194]
**Is your feature request related to a problem? Please describe.**
Not a problem just an enhancement if you will. It would be great if we can have a 12h cooldown to appear after a successful vote in the list shown by $timers command. 

**Describe the solution you'd like**
Perhaps the cooldown can be added to the function/part where message of a successful vote is being sent to the DM. So It will be easier to remember when to vote next time. 

**Describe alternatives you've considered**
An alternative could be that the bot sends a message after 12h of last successful vote reminding the player that *"They can vote again to get a chance of winning the mysterious legendary crate".*

**Comment by Gelbpunkt** [comment]
done
