### ISSUE TITLE
Pet food/drink - Improving item progression or >1 unit purchase in one command

### ISSUE THREAD

**Issue by Jhevad** [Gelbpunkt/IdleRPG#195]
**Is your feature request related to a problem? Please describe.**
Thirst to $ ratio does not improve as drinks get more expensive, forcing the poor or the $-conscious to use $pet drink multiple times (buying water, best thirst/$ ratio), being a spammy and/or tedious process.

**Describe the solution you'd like**
Either a) create an improving progression for food/drinks in terms of efficiency, or b) if one does not want to reward less frequent feeding to pet, a way to feed/drink multiple times in one same command instead of selecting from emojis multiple times.

**Describe alternatives you've considered**
Keep playing as is using channels I know I won't spam.

**Additional context**
Thanks for considering this.

**Comment by Gelbpunkt** [comment]
Changed
