### ISSUE TITLE
Active Adventure breaks when fighting an enemy.

### ISSUE THREAD

**Issue by Aramythia** [Gelbpunkt/IdleRPG#197]
**Describe the bug**
Clicking on the emotes gets no response when attempting to move onto an enemy's tile. The adventure freezes and you can't make any other move.

**To Reproduce**
1. Find a cell with an enemy in it
2. Try going in the direction of that cell

**Comment by Gelbpunkt** [comment]
Cannot reproduce

**Comment by Gelbpunkt** [comment]
No information provided, closing
