### ISSUE TITLE
$chat bug

### ISSUE THREAD

**Issue by shintarowo** [Gelbpunkt/IdleRPG#199]
**Describe the bug**
$[talk|cb|chat] <text> doesn't seem to work in any server that has IdleRPG invited.

**To Reproduce**
1. Go to any server that has IdleRPG invited.
2. Enter command - $[talk|cb|chat] <text>

**Expected behavior**

**Screenshots**
![idle chat bug](https://user-images.githubusercontent.com/52795906/63984179-f1f8d600-ca97-11e9-81fc-40d1c57e233c.PNG)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Gelbpunkt** [comment]
Next time report this in the TraviAPI server please. I restarted the API and now it's working
