### ISSUE TITLE
$5k is not deducted after pet dies or runs away and you choose Ranger again

### ISSUE THREAD

**Issue by Nanashi7404** [Gelbpunkt/IdleRPG#202]
**Describe the bug**
Not sure if this is intentional or not but if your pet dies or run aways, and you choose ***Ranger*** class again, $5000 doesn't get deducted.

**To Reproduce**
1. Make sure you have less than $5000 on your character 
1. Do '*$class* and choose Ranger again once your pet runs away or dies.

**Expected behavior**
If a character has enough money it should be deducted, else they should get a message telling them they don't have enough money for selecting a class 

**Screenshots**
![image0-2](https://user-images.githubusercontent.com/54116487/64010722-caefe200-cb33-11e9-8bdc-8bcdce3d66b7.png)

**Comment by forceeeee** [comment]
I noticed this but diddint think of repicking ranger again lol

**Comment by Gelbpunkt** [comment]
Intended.
