### ISSUE TITLE
bug in $adventures success rate calculation 

### ISSUE THREAD

**Issue by Tirvanel** [Gelbpunkt/IdleRPG#204]
**Describe the bug**
When my luck is set to 2, $adventures displays a lower success chance than when my luck is set to 0. 

**To Reproduce**
Set luck to 2, run $adventures, check success rates 
Set luck to 0, run $adventures, check success rates

**Expected behavior**
Higher success rate at 2 luck than 0 luck.

**Screenshots**
0 luck: ![714579C6-EDE8-44CB-8A20-9F7065AE3AD3](https://user-images.githubusercontent.com/9456025/64031996-93733c80-cb17-11e9-97b3-2319980a80ae.jpeg)
2 luck:
![1959B341-1209-4A5B-8592-C1B1D39E7853](https://user-images.githubusercontent.com/9456025/64032031-9f5efe80-cb17-11e9-9b6a-6ff21a9bb5f7.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 13 I think?
 - Browser Discord app

**Additional context**

**Comment by Tirvanel** [comment]
Looking at code, this appears to be a simple order of operations mistake where luck is only being multiplied by the dungeon level*2 and dungeon level*10 bit, rather than the whole calculation.

**Comment by Gelbpunkt** [comment]
Fixed in e1df666
