### ISSUE TITLE
Buy ur items in market

### ISSUE THREAD

**Issue by Quinemaniac** [Gelbpunkt/IdleRPG#207]
**Describe the bug**
U can buy ur items in the market and it will DM u that urself buy it 

**To Reproduce**
1. Do `$sell <itemid> <prize>`
2. type $buy the item u just added

**Expected behavior**
it will dm u that u bought it 

- U should forbid people to buy their own item in market or if u allow it, i think the command $remove isnt necessary

**Comment by Gelbpunkt** [comment]
Fixed in 4.1
