### ISSUE TITLE
Money disappeared from a character's bank.

### ISSUE THREAD

**Issue by ToastGhost1** [Gelbpunkt/IdleRPG#208]
In the past 24 hours (8/31/2019 5:26 PM EST) my friend Lolita (602499230460018708) went from $181676 to $52047 for seemingly no reason. No commands were used to lower the total amount of money on her character, nor is it possible for a thief to have done this. Shintaro reviewed this and thinks that it was a bug, and suggested I report this, here. (thanks 

**Steps to reproduce the behavior:**
1. Be unlucky as h*ck

**Expected behavior**
it not to do this.

**Screenshots**
https://cdn.discordapp.com/attachments/596373153077395457/617461735368163358/Profile.png
https://cdn.discordapp.com/attachments/596373153077395457/617461790942691348/Profile.png

**Additional Context**
Shintaro deserves a high five

**Comment by Quinemaniac** [comment]
literally, i dont think it is bug, try to ask ur friend again 
i never get this bug

**Comment by Gelbpunkt** [comment]
I agree with Quinella. There's no reason why it'd disappear magically. Either this is a trick to gain money or you forgot you spent it.
