### ISSUE TITLE
Offer urself a item 

### ISSUE THREAD

**Issue by Quinemaniac** [Gelbpunkt/IdleRPG#209]
**To Reproduce**
1. Do '$offer [itemid] [prize] [urself]'
3. Accept that offer 

**Expected behavior**
it will take ur item, money then give back to u

**Additional context**
U should forbid people to offer themselves

**Comment by 1InnocentKiller** [comment]
Or fix it,because new people are going to keep joining and might do the same while being unaware

**Comment by Gelbpunkt** [comment]
Fixed in v4.1
