### ISSUE TITLE
$child, 2 child with the same fate.

### ISSUE THREAD

**Issue by zweiyang** [Gelbpunkt/IdleRPG#212]
**Describe the bug**

2 child with the same name different gender and every $familyevent if what happened to one of them happens to the other.

**To Reproduce**
1. Do '....'
2. Enter command '....'
3. Hit reaction '....'

Both couple enter $child and accept together each invite. And both invite succeeded in giving birth to a child and then asking for a name for the child. 

Only one name got registered for both of them.

**Expected behavior**

The first name called by the any parent will be registered for the first child to be born and the second one would be for the child birth last.

**Screenshots**

![Screenshot_2019-09-01-21-43-57-98](https://user-images.githubusercontent.com/54771246/64077658-07bf0300-cd05-11e9-9f62-e61e1b5ccc8d.png)

![Screenshot_2019-09-01-21-44-49-94](https://user-images.githubusercontent.com/54771246/64077666-14dbf200-cd05-11e9-874f-0e1882f77dc9.png)

![Screenshot_2019-09-01-21-46-37-53](https://user-images.githubusercontent.com/54771246/64077669-1c030000-cd05-11e9-8feb-53cc414a14c5.png)

![Screenshot_2019-09-01-21-46-42-51](https://user-images.githubusercontent.com/54771246/64077673-2624fe80-cd05-11e9-8cb9-0628a087264f.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

Device: OPPO F5
OS: Android 7.1.1
Browser: Google Chrome
Version: CPH1723EX_11.A13_190702

![Screenshot_2019-09-01-22-20-30-81](https://user-images.githubusercontent.com/54771246/64077841-bf084980-cd06-11e9-9c0c-44051ac5c2a4.png)

**Additional context**

**Comment by Gelbpunkt** [comment]
Should be fixed
