### ISSUE TITLE
Custom prefix broke the bot

### ISSUE THREAD

**Issue by Defenestrate-flof** [Gelbpunkt/IdleRPG#214]
**Describe the bug**
Bot wont respond on custom prefixes.

**To Reproduce**
1. Do: $prefix [anything]
2. Try to do anything with new prefix

**Expected behavior**
Bot should respond to the new prefix change. 

**Screenshots**
![86BD95C9-0433-48E8-BC80-BF0282903655](https://user-images.githubusercontent.com/52734271/64080084-3e534880-cd1a-11e9-9e81-11e831a6c564.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone7 Plus
 - OS: iOS12.4
 - App: Discord
 - Version 3.1.1

**Additional context**
Many people have the same issue and they are flocking in #support demanding compensation ;;^;;

**Comment by Gelbpunkt** [comment]
should be fixed
