### ISSUE TITLE
Boosters for guild raid

### ISSUE THREAD

**Issue by BrownIndianGuy** [Gelbpunkt/IdleRPG#215]
**Is your feature request related to a problem? Please describe.**
Most of the guild raid take  long time when time goes we need a way to reduce time

**Describe the solution you'd like**
1) time booster :using this guild leader can reduce guild raid time. Uses guild money
2)time skip : it can be guild side or /&  player side. Player/leader can by time skipper using which they can skip a few time fromraid.eg: using a 1k  skip 5-10 minutes can be skipped.

**Describe alternatives you've considered**
Something to reduce raid time

**Additional context**

**Comment by Gelbpunkt** [comment]
It's adventure what you meant, I suppose. And no, they bring loads of money and the time is crucial for it to be a fair ratio
