### ISSUE TITLE
$pet cuddle doesnt give love but goes on cooldown

### ISSUE THREAD

**Issue by Defenestrate-flof** [Gelbpunkt/IdleRPG#216]
**Describe the bug**
One player said the command cooldowns start without giving them any notifications or love points.

**To Reproduce**
1. Do $pet cuddle

**Expected behavior**
Bot should have give love points and notifications.

**Screenshots**
![134B1B55-74FD-4200-BBED-86A935750037](https://user-images.githubusercontent.com/52734271/64101308-c9265880-cd97-11e9-8ab7-81e261235133.jpeg)
![19950F3B-F0F3-4290-B1CD-CA655FBF296E](https://user-images.githubusercontent.com/52734271/64101309-c9265880-cd97-11e9-94c3-9035f3e772bb.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone7 Plus
 - OS: iOS12.4
 - Browser: Discord
 - Version 3.1.1

**Additional context**
This was done after the update [at least within 24h from now]. 
The second pic was after all the commands was done btw.
The player didn’t gave me a pic before the command was done since they doesnt check $pet.

**Comment by Gelbpunkt** [comment]
I cannot reproduce this

**Comment by Defenestrate-flof** [comment]
Guess imma close it then.
