### ISSUE TITLE
Gods not able to selectively give followers luck.

### ISSUE THREAD

**Issue by Athuna** [Gelbpunkt/IdleRPG#221]
So I tried giving luck to someone who is not in the server with the SetLuck command and it gave me a "Malformed Argument" not sure if this is fixable, but i felt like it should be pointed out.

**Comment by forceeeee** [comment]
There is a slightly similar problem to this that was fixed I the latest update. It was if you do a command to make a child in a server where your spouse wasant in, you can react accept yourself and make a baby without the spouse reacting. If that got fixed, this will too.

**Comment by Gelbpunkt** [comment]
That's because they don't have a character anymore or aren't visible to any of the bot processes
