### ISSUE TITLE
[Suggestion] Pet Rework for less stress, deathless but still requiring stats for hunt

### ISSUE THREAD

**Issue by DShou** [Gelbpunkt/IdleRPG#222]
**Is your feature request related to a problem? Please describe.**
As of currently the pet stats seem to decrease at a rate that requires tamagotchi level of attention, especially with the love stat where with bad luck can result in unavoidable pet death. Unfortunately this makes the hunter class significantly more demanding compared to other classes.

**Describe the solution you'd like**
The stats can be kept, however instead of death the pet can be in a disobedient mode instead when reaching 0 in a stat. This can then disable pet commands such as hunt until the player reaches, say, 30 in every stat again or such.

**Describe alternatives you've considered**
Alternatively, the cuddle and play command can be more reliable such as food and drink - and with stats decreasing at a more forgiving rate. However as someone who likes the pet system, but is unable to check on discord so frequently, would still prefer the deathless suggestion.

**Additional context**
N/A

**Comment by Gelbpunkt** [comment]
Should be "more forgiving"
