### ISSUE TITLE
Floating point errors in luck result in messy output

### ISSUE THREAD

**Issue by numbermaniac** [Gelbpunkt/IdleRPG#224]
**Describe the bug**
$luck produces lots of unnecessary floating point error digits sometimes.

**Expected behavior**
Rounded decimals, perhaps?

**Screenshots**
![Screen Shot 2019-09-05 at 11 12 01 am](https://user-images.githubusercontent.com/5206120/64304015-1a1f9200-cfce-11e9-8bc0-8e9fb6241f17.png)

**Additional context**
Maybe the Decimal library can be used, or perhaps just round() the float?

**Comment by Gelbpunkt** [comment]
Should be fixed
