### ISSUE TITLE
Facts or tips command.

### ISSUE THREAD

**Issue by forceeeee** [Gelbpunkt/IdleRPG#225]
**Is your feature request related to a problem? Please describe.**
Add a $tip command and you get a random tip for the game, this will help newer players with the game and we will receive less questions like: what can I do with my items that I don't need?

**Describe the solution you'd like**
Add a huge list of tips and when you do $tip , it picks a random one and tells you.

**Describe alternatives you've considered**
If this idea is approved, I will make a big list of tips.

**Additional context**

**Comment by Defenestrate-flof** [comment]
We already have $tutorial command to help new players with the basic tho.

**Comment by forceeeee** [comment]
Yea but that clearly doesn't cover everything

**Comment by numbermaniac** [comment]
That's why we're making the IdleRPG Wiki, which is a work in progress. https://wiki.travitia.xyz/

**Comment by forceeeee** [comment]
Yea but it would be nice to have a one sentence tip here and there

**Comment by forceeeee** [comment]
By the feedback I'm getting i think it's gonna get closed lol
