### ISSUE TITLE
Adventure from previous character

### ISSUE THREAD

**Issue by Ossta** [Gelbpunkt/IdleRPG#226]
**Describe the bug**
I removed my character, created new one, was ready to start first adventure (on new accout), typed $a 1 and then i've been showed that adventure is already started and it is 12 (when im lvl1, i was 12lvl on previous account).

**To Reproduce**
1. Do : Delete account, create new one
2. Enter command : $a 1
3. Hit reaction dunno what it means

**Expected behavior**
I expected it to be adventure 1

**Screenshots**
![image](https://user-images.githubusercontent.com/54947420/64350912-b8751d00-cff9-11e9-94d1-52b5c3defbb3.png)

**Desktop (please complete the following information):**
PC, DISCORD

**Smartphone (please complete the following information):**
PC, DISCORD

**Additional context**

**Comment by Gelbpunkt** [comment]
You can do `$cancel` until I make the bot cancel adventures on character deletion

**Comment by Gelbpunkt** [comment]
Fixed
