### ISSUE TITLE
Guild Ownership

### ISSUE THREAD

**Issue by hermes-motorad** [Gelbpunkt/IdleRPG#227]
**Feature Request**
Suggestion of a feature where you can _transfer_ guild ownership. It can be a transfer, promotion, or successor-like system--any as long as the guild isn't gone even if the guild owner decides to quit by deleting. 

**Comment**
Found out that the guild ownership isn't kept to the account itself, and it doesn't get transferred to a officer (only one when I was testing) when the owner deletes their character. Since upgrading guild bank (and member capacity for patreons) costs money, it's a big waste for both the owner and the member of the guild when the owner deletes it, intentional or not.

**Comment by maxx0911** [comment]
Maybe like this:
When a guild leader deletes, the guild leader is set to `None`
Once the leader is `None`, any guild member can use `$guild claim` where they will claim the guild ownership and become the new leader.
Alternatively, a second-in-command guild member status.

**Comment by hermes-motorad** [comment]
That's not a nice method because it means _anyone_ can be the guild owner. What if they're a troll? What if there is money in the bank and the one who was lucky to claim the ownership gets it all and just delete off the guild? It's better for the primary guild owner to decide, or transfer ownership. If transferring, for example, you can have it a system where you can promote them once more to be a successor. Just have a confirmation message so there'll be no(or less) mistake promotions.
Also, I don't really see the need for second-in-command when there is already a guild officer. They can do mostly everything anyways.

**Comment by maxx0911** [comment]
You have to take into consideration though, that not all guild leaders just delete their characters/accounts with a conscious decision. My guild leader for example cannot access his main discord account and wouldn't be able to transfer ownership.

While I do like your suggestion, it doesn't account for cases like above.

**Comment by hermes-motorad** [comment]
That's why I suggested for a promotion above guild officer so when the guild owner deletes their character, be it _intentional or not_ , the next owner would be the successor - or the highest promoted member that isn't the guild owner. I don't know about the part not being able to access your account or not, that's a different issue. I'm talking about transfer here of when they delete their account/character.

**Comment by Gelbpunkt** [comment]
Added.

**Comment by hermes-motorad** [comment]
Thank you! This was really helpful :)
