### ISSUE TITLE
Luck rebalance

### ISSUE THREAD

**Issue by Stevelion** [Gelbpunkt/IdleRPG#228]
**Is your feature request related to a problem? Please describe.**
Lower level players can't even finish the lowest adventures with low luck

**Describe the solution you'd like**
Rebalance luck to make it affect adventure success less (maybe half as much)

**Describe alternatives you've considered**
Restrict gods from setting luck too low for any extended period of time

**Comment by Gelbpunkt** [comment]
That's how luck is intended.
