### ISSUE TITLE
Pet cuddle issue

### ISSUE THREAD

**Issue by maxx0911** [Gelbpunkt/IdleRPG#229]
**Describe the bug**
The `$pet cuddle` command goes on cooldown occasionally, even though the command itself doesn't trigger. It might have something to do with custom prefixes, however the reason behind it is unclear.

**To Reproduce**
1. Assign the Ranger (primary) class
2. `$pet cuddle` - reportedly `$pet hunt` too
3. Use the command again if there is no output to see it is now on cooldown.

**Expected behavior**
The respective pet subcommand should output the message and update the values in the database, i.e. raise the love stat when using `$pet cuddle`

**Screenshots**
[Screenshot 1 (doesn't trigger)](https://cdn.discordapp.com/attachments/430017996304678925/619617005124714496/HljlKSeEKgcwJH1WXuvGhylRAgBAiBE4sA6b6eWML1JYQIASOIwEiEI8jXFI0IUAInFgEiEA8sZ4XqS0hQAgcRwJEIB5HuKRoQoA.png)
[Screenshot 2 (doesn't trigger again)](https://cdn.discordapp.com/attachments/430017996304678925/619617217667137579/bakiQtdFEaAIXC0EKB9dLeTpeykCFIHpCPwf75rXla8HBjAAAAAASUVORK5CYII.png)
[Screenshot 3 (Command works as intended)](https://cdn.discordapp.com/attachments/430017996304678925/619617587508150312/wdYeG914HqTpgAAAABJRU5ErkJggg.png)

**Desktop (please complete the following information):**
 - OS: [varying]
 - Browser Chrome
 - Version [varying]

**Smartphone (please complete the following information):**

**Additional context**
This bug report was made for User `metalcupcake5
#6942 (377551134702829568)`, please contact them for any more details.

**Comment by Gelbpunkt** [comment]
I need message IDs where this happened

**Comment by metalcupcake5** [comment]
ID: 618535402323574805
![image](https://user-images.githubusercontent.com/43897385/64490614-8b9c5200-d213-11e9-8358-0fe6c4e7afee.png)

ID: 615208497847730196
![image](https://user-images.githubusercontent.com/43897385/64490628-acfd3e00-d213-11e9-9004-55adfe42b08f.png)

I can find more if you need them

**Comment by Gelbpunkt** [comment]
I'm very sorry - I'll need a message ID, channel ID and guild ID. Additionally, the user must be a ranger

**Comment by metalcupcake5** [comment]
Message id: 615208497847730196
Channel: 610192327859765250
guild: 330048077467615232
![image](https://user-images.githubusercontent.com/43897385/64923700-55ba1900-d791-11e9-9105-26e411f8f0ab.png)

message: 615629847011524629
channel and guild are the same
![image](https://user-images.githubusercontent.com/43897385/64923716-9b76e180-d791-11e9-9759-655e5bab9502.png)

message: 617558043969978368
channel and guild same
![image](https://user-images.githubusercontent.com/43897385/64923737-d2e58e00-d791-11e9-9595-8059f9be0a5a.png)


I am a ranger, my user id is 377551134702829568 if you  need it

**Comment by Gelbpunkt** [comment]
Fixed it seems
