### ISSUE TITLE
Buff Ritualist 

### ISSUE THREAD

**Issue by forceeeee** [Gelbpunkt/IdleRPG#242]
**Is your feature request related to a problem? Please describe.**
You get a 25% sacrifice bonus when you are MAX level? The ritualist is weak and almost useless, the only good part is for events, other than that, 25% bonus to a thing you get in a 1/10 chance is just ridiculous.

**Describe the solution you'd like**
Buff the bonus for sacrifices. It should be: 10% 20% 30% 40% 50%, Because there are way better classes and practically no one uses ritualist.
**Alternative**
Increase the chance for getting loot from adventures, this would also be a 10% increase per evolution, if both is too op, just add 1 of the 2.

**Comment by Gelbpunkt** [comment]
It's 2/10 for Ritualists

**Comment by forceeeee** [comment]
Fair enough,  but please add more bonus

**Comment by Gelbpunkt** [comment]
It's already enough bonus, the current bonus is equal to what you described

**Comment by forceeeee** [comment]
Equal to what I described? It increases by 5%, my suggestion is to make it 10%

**Comment by Gelbpunkt** [comment]
Getting one of of 10 items with 50% bonus is worse than two out of 10 with 25% bonus

**Comment by Stevelion** [comment]
Unless I'm misunderstanding the code, ritualist makes it randint(2,10), so 1/9 not 2/10.

**Comment by Gelbpunkt** [comment]
2/10 equals 20%, randint doesn't work like range

**Comment by Gelbpunkt** [comment]
Nvm you're right, I will change that tomorrow

**Comment by Stevelion** [comment]
random.randint(a, b)
Return a random integer N such that a <= N <= b.
Taken from docs.python.org/2/library/random.html

**Comment by Gelbpunkt** [comment]
Fixed
