### ISSUE TITLE
Unreadable name Married to:

### ISSUE THREAD

**Issue by idle-Mercy** [Gelbpunkt/IdleRPG#243]
**Describe the bug**
My spouse has a name that is unreadable in the bot. The discord name itself can't be read by idlerpg, but his character name is okay. 

![](https://cdn.discordapp.com/attachments/565702840098750484/621353268001505284/Profile.png)

![image](https://user-images.githubusercontent.com/52788111/64707421-f7372700-d480-11e9-8a23-1ad0a15242ba.png)

**Proposed Solution**
Make it so instead of the discord name, you see the character name, that way if the person's username is not able to be read by discord because they use characters/symbols that don't exist in the bot, the married person's background isn't ruined because of that.

**Comment by idle-Mercy** [comment]
https://cdn.discordapp.com/attachments/565702840098750484/621353268001505284/Profile.png

**Comment by Gelbpunkt** [comment]
Character names potentially contain non-ascii symbols as well

**Comment by Gelbpunkt** [comment]
Can you copy paste the username here? I got an idea

**Comment by Gelbpunkt** [comment]
no response
