### ISSUE TITLE
Magic Casters (mages) suggestion

### ISSUE THREAD

**Issue by Clubjogos** [Gelbpunkt/IdleRPG#244]
**Is your feature request related to a problem? Please describe.**
There's a Mage class on the bot but there's no spells, it's frustrating becoming a Mage but not able to use spells.

**Describe the solution you'd like**
Magic items, staffs and all the magic casters related stuff such as spells and magical skills. I'd appreciate too much if you consider using at least most of the spells from https://overlordmaruyama.fandom.com/wiki/Tier_Spells and some inspiration on other Overlord's magical stuff.

**Describe alternatives you've considered**
Remove the mage class.

**Additional context**
https://overlordmaruyama.fandom.com/wiki/Tier_Spells
https://overlordmaruyama.fandom.com/wiki/Items

**Comment by Gelbpunkt** [comment]
not a v4 content

**Comment by forceeeee** [comment]
This isn't a update that will be done in the near future, Adrian said he will do skills and all that kinda stuff in v5.0, its v4.1.2 right now and v5.0 will not come atleast by the end of this year.

**Comment by Clubjogos** [comment]
> This isn't a update that will be done in the near future, Adrian said he will do skills and all that kinda stuff in v5.0, its v4.1.2 right now and v5.0 will not come atleast by the end of this year.

Ok got it now, ty
