### ISSUE TITLE
no_merch item flag

### ISSUE THREAD

**Issue by Jhevad** [Gelbpunkt/IdleRPG#246]
**Is your feature request related to a problem? Please describe.**
It'd be useful to have a way to flag certain item IDs as "no_merch", in order to protect them from accidental sale through merchall. Specially useful when inventory is holding a lot of items and a merchall is required and a few items prevent liquidation of the many.

**Describe the solution you'd like**
Being able to set a safe or unsellable flag on an item so that it prevents it from being sold or exchanged. The flag is toggable by the item's owner.

**Describe alternatives you've considered**
Manually clear inventories by hand, although it is much more time consuming and still prone to some errors.

**Comment by Gelbpunkt** [comment]
To circumvent adding a new column to the database, you can now merch multiple items at once instead of flagging for merchall. This is too much effort for too little profit
