### ISSUE TITLE
Pending items disappear? 

### ISSUE THREAD

**Issue by Jaegothis** [Gelbpunkt/IdleRPG#250]
**Describe the bug**
In this bug, items seem to disappear from people's $pending without them getting a notification or doing $remove.

**To Reproduce**
I'm not completely sure, as it seems to be random. 

**Expected behavior**
I expect that we don't lose items without a notification of sorts. 

**Screenshots**
I don't have screenshots of them disappearing, as that would be impossible, but here are two users that experienced the issue. 
![image](https://user-images.githubusercontent.com/54690879/64829801-c7c90d00-d59b-11e9-8086-fa5aafc7b965.png)
![image](https://user-images.githubusercontent.com/54690879/64829839-f6df7e80-d59b-11e9-860d-5cb73237fb03.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Comment by Gelbpunkt** [comment]
May be because you had DMs disabled. Apart from that, @TheKerrigan0808 is right
