### ISSUE TITLE
$race add-ons

### ISSUE THREAD

**Issue by shintarowo** [Gelbpunkt/IdleRPG#251]
**Is your feature request related to a problem? Please describe.**
no, but it'll be more accessible if you add on "You're of the (race) race." to the command ``$race``

**Describe the solution you'd like**
add the info "You're of the (race) race." to $race so it provides another way of viewing your race apart from ``$pp``

**Describe alternatives you've considered**

**Additional context**

**Comment by Gelbpunkt** [comment]
Will be added to `$profile` today/soon
