### ISSUE TITLE
ln Between Cooldowns 

### ISSUE THREAD

**Issue by ardainanir** [Gelbpunkt/IdleRPG#252]
**Is your feature request related to a problem? Please describe.**
l don't want to wait 2 sec for every command.
**Describe the solution you'd like**
If bothers someone he can put slow mod in his channel so lt will be solved but in many servers there is no need for that l believe.
**Describe alternatives you've considered**
the best solution is putting slow mod in channel l believe. 
**Additional context**
I'm not talking about just cooldowns like daily l'm talking about $s $s cooldowns please please please do not put cooldowns on inbetween commands

**Comment by maxx0911** [comment]
You have to think about this. If there was no general cooldown, people would send multiple commands in one second, especially with the short command names.
If everyone in all the 100,000 servers would do that, the bot would have to process multiple hundreds of thousands of commands per second.
I'm not sure if you've seen some of the lag spikes it has, but when you take away the general cooldown, the lag spikes can go from 20 seconds to *multiple minutes*. I'm not sure if you really want that.
