### ISSUE TITLE
new background profile idea

### ISSUE THREAD

**Issue by Quinemaniac** [Gelbpunkt/IdleRPG#256]
**Is your feature request related to a problem? Please describe.**
I feel that the new profile is too narrow but it has many lines for god, race, etc..., that makes me feel uncomfortable

**Describe the solution you'd like**
I think we should make it bigger size like 720x1080 so we can still put some lines there and still feel comfortable

**Comment by hermes-motorad** [comment]
Thank you for putting effort in the new profile idea but...adding to this, I'm left-handed so it doesn't really fit? Not a hell big deal, I know, but I think it's better to merge the stats and the names like how it was done in the previous profile, also removing the right and left hand texts for more space. Thanks!

**Comment by Gelbpunkt** [comment]
Size increase won't happen. A bigger size means creating the image takes far longer, and I don't want to hurt UX.
