### ISSUE TITLE
Choice between new and old profile background 

### ISSUE THREAD

**Issue by Nanashi7404** [Gelbpunkt/IdleRPG#259]
**Is your feature request related to a problem? Please describe.**
After profile backgrounds were updated, alot of the people on support server are saying that they liked the old ones better. Some do like the new one too. Can we please have a choice between new and old backgrounds? 

**Describe the solution you'd like**
A command that can will allow you to switch back and forth from old and new styles of profile background. $profileold or $po could be used?? 

**Additional context**
Suggestion was originally made by Sniper#1771 userid: 500495777366540290 in support channel.

**Comment by maxx0911** [comment]
people with eventbackgrounds are also experiencing this problem.
maybe adding to this there could be a way to detect the image dimensions and if they're equal to the old profile dimensions, then apply the text like it was for the old profile, so that all the eventbackgrounds aren't just obselete.

**Comment by Gelbpunkt** [comment]
This change was planned for a whole year already, I am not offering a way to get an old, outdated and ugly profile.
