### ISSUE TITLE
Old evenbackground still accessible and $eventbackground 0 not working 

### ISSUE THREAD

**Issue by Nanashi7404** [Gelbpunkt/IdleRPG#260]
**Describe the bug**
People who won eventbackgrounds are still able to access them and use them the overlay is not compatible with new background style. "$eventbackground 0" is also not reverting background back to new format. "$background reset" works though. 

**To Reproduce**
1. Choose an eventbackground
2. Check profile ($p)
3. Do $eventbackground 0 
4. Do $background reset

**Expected behavior**
If the change in format is final, then old eventbackgrounds should be deleted. Or the overlay could be adjusted for new format if the people at design team can manage that. 

**Screenshots**
![Profile](https://user-images.githubusercontent.com/54116487/64926795-3ec00900-d81b-11e9-84a0-4ce9de158723.png)

**Comment by Gelbpunkt** [comment]
The change is final, but I don't want to wipe the eventbackgrounds as they're still good memories
