### ISSUE TITLE
$vote bug issue 

### ISSUE THREAD

**Issue by shintarowo** [Gelbpunkt/IdleRPG#262]
**Describe the bug**
Users (myself included) have been experiencing the bug of when you vote, you receive two crates whereas normally you're suppose to receive one. 

**To Reproduce**
1. Do $vote
2. click link provided
3. vote, and wait for the bug (it occurs sometimes)

**Expected behavior**
To receive one crate of some sort of rarity instead of two

**Screenshots**
https://media.discordapp.net/attachments/430017996304678925/622897766720471180/image0.png?width=400&height=239
https://media.discordapp.net/attachments/430017996304678925/622897767324319784/image1.png?width=337&height=301

**Desktop (please complete the following information):**
 -  iOS
 - Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Gelbpunkt** [comment]
Cannot reproduce over several days
