### ISSUE TITLE
Asking permission for area 51 event

### ISSUE THREAD

**Issue by maxx0911** [Gelbpunkt/IdleRPG#265]
**Is your feature request related to a problem? Please describe.**
My request is not related to a problem. I would like to make an `$adventure 51` command, for the meme event coming up on September 20th.

**Describe the solution you'd like**
I would like to have your permission to work toward making this command, since I don't want to sit around coding, just for it to be not accepted.
When I get that permission, I will propose file changes soon.

**Describe alternatives you've considered**
An alternative I have considered is not doing it.

**Additional context**
If you were already planning on doing something like that, I'll gladly leave the coding up to you, since we probably have very different ideas of it.

**Comment by Gelbpunkt** [comment]
Sure you may work on this :) I got no plans and no clue what it is, so I'll be happy to review the code when you're done!

**Comment by maxx0911** [comment]
Hope I can be done by the 20th :)

**Comment by maxx0911** [comment]
I do have one question about it though:
[Here](https://github.com/Gelbpunkt/IdleRPG/blob/v4/cogs/adventure/__init__.py#L388) it mentions the adventure names from config, however in the `config.py.example` it doesn't show this. I'd just like to know if this is a list/tuple or a dictionary?

**Comment by Gelbpunkt** [comment]
https://github.com/Gelbpunkt/IdleRPG/blob/v4/config.example.py#L188

**Comment by maxx0911** [comment]
Welp, looks like I'm actually blind 😬 
Thanks for the info though, that should be all I need
