### ISSUE TITLE
Event Background Fix

### ISSUE THREAD

**Issue by ClaryRPG** [Gelbpunkt/IdleRPG#267]
**Is your feature request related to a problem? Please describe.**
Every time a new layout is made, everyone with an event background loses their event background or it looks really bad with the new layout.

**Describe the solution you'd like**
Give us a command we can use to fix the layout of the background. We do a command and the bot checks if we have an event background. If we do, it will put the new layout on it. We'll have to remember which event background number it is. But it would mean the devs don't have to do the bulk of the work finding out who has an event background and fixing it themselves. 

**Describe alternatives you've considered**
Or even just the command $eventbackground 1 will make the background we had with the new layout. The last event wasn't so long ago, and the winners would love to show off that they won an event. It'd fix it for everyone who had an event background and make them more inclined to participate in events. 

**Additional context**
I did like the old layout better, but the ability to still have your event backgrounds will make the transition a little easier every time you do a new layout so everyone is happy. 

Thank you for reading.

**Comment by forceeeee** [comment]
They already declined multiple posts talking about the same thing. I doubt they will accept your post.
Enjoy your post being active for the last few days it gets unnoticed by @Gelbpunkt

**Comment by ClaryRPG** [comment]
I guess people ask because it's something they want. Sucks to win an event only for your prize to go away, especially if it's something that's fixable. I gave some ideas on how to fix the issue. Hopefully they listen,  or even just do it that way going forward.

**Comment by Gelbpunkt** [comment]
we store the final image only, not the actual background image so there's no way to actually do this
