### ISSUE TITLE
Unfinished Idea?

### ISSUE THREAD

**Issue by forceeeee** [Gelbpunkt/IdleRPG#269]
![Profile-1](https://user-images.githubusercontent.com/53173499/65033907-34a52400-d95b-11e9-917e-8a8c361441d4.png)

To the Left of **race** and **name** there seems to be a square shaped peice of darkness. It seems as if it's an idea that was just not done. I suggest making a pfp of some sort in that area, since its a pretty big peice of unused space.

**Comment by Slavis-from-Idle** [comment]
I think it should be a avatar of your character. Im wondering, what will be SP (Spell Points)? Also, what is planned to be in between gold and god.

**Comment by forceeeee** [comment]
In between Gold and God? Also we don't know what SP is, the developer's just teased us with an upcoming feature

**Comment by Gelbpunkt** [comment]
SP = skill points
that thing = your current position on the map
the big thing will be used soon when we managed to finish our server migration

**Comment by Gelbpunkt** [comment]
Skins made this clear and will come soon.
