### ISSUE TITLE
xp booster

### ISSUE THREAD

**Issue by Quinemaniac** [Gelbpunkt/IdleRPG#272]
**Is your feature request related to a problem? Please describe.**
I heard many people complaining that level up from lv 17 to 20 is too hard 

**Describe the solution you'd like**
i want to request new booster : xp booster that we can get extra 10% xp from adventure, that should cost 1000+$

**Comment by forceeeee** [comment]
It's an RPG game, what do you expect? It should stay the same, every RPG is like that, the last few levels are the hardest. But the idea is alright, just kinda ruins the "grind" imo

**Comment by forceeeee** [comment]
.

**Comment by forceeeee** [comment]
Hi people viewing github

**Comment by Gelbpunkt** [comment]
this is IdleRPG, not RushToTheTopRPG :) on the long run, you'll turn level 20 one day
