### ISSUE TITLE
A new crate

### ISSUE THREAD

**Issue by Viper-ai** [Gelbpunkt/IdleRPG#274]
A new crate idea: loot crate.
Drop chance is a bit lower then uncommon and drops any loot. Since it's all god stuff it won't really interfere with the main leveling up

**Comment by forceeeee** [comment]
I totally agree with this, because it would be nice to be able to buy loot. But then again,  rich people can just spam  buy them and people won't have a chance to get the god rewards, so it needs to have a low loot drop table.

**Comment by forceeeee** [comment]
The highest loot you can get should be 100

**Comment by forceeeee** [comment]
Even that might be too much, if it costs like 1k each then it might be good, but if it costs a few hundred, its too op

**Comment by maxx0911** [comment]
let me just leave [this](https://github.com/Gelbpunkt/IdleRPG/issues/180#issuecomment-526855205) here

**Comment by forceeeee** [comment]
Good thing it's a rejected post

**Comment by forceeeee** [comment]
Dont want people to abuse it

**Comment by Gelbpunkt** [comment]
I agree with @max0911 and didn't change my opinion yet :)
