### ISSUE TITLE
Changing a Guild Name

### ISSUE THREAD

**Issue by DragonSlayer3454** [Gelbpunkt/IdleRPG#277]
**Is your feature request related to a problem? Please describe.**
(N/A)
**Describe the solution you'd like**
(N/A)
**Describe alternatives you've considered**
(I am sure the IdleRPG community would like for there to be a command to change/rename a guild name.)
**Additional context**
(N/A)

**Comment by terror-kvothe** [comment]
please answer all of the questions

**Comment by numbermaniac** [comment]
You can't just ignore the whole damn template by writing "N/A" under every single question and then expect us to take your issue seriously.

**Comment by maxx0911** [comment]
![image](https://user-images.githubusercontent.com/47576240/65333227-60751380-dbc0-11e9-9670-fda8ff471db4.png)

**Comment by Gelbpunkt** [comment]
Lol
