### ISSUE TITLE
Additional, optional, personal guild bank accounts

### ISSUE THREAD

**Issue by Slavis-from-Idle** [Gelbpunkt/IdleRPG#278]
**Is your feature request related to a problem? Please describe.**
Guild bank is a great idea to protect player funds from being stolen, however, it generates a problem, when few guild members want to use it together, but keep track of their personal share of gold. It forces the players to keep detailed notes, who moves what amount of money in with direction (in or out). Creating a possibility to store that money separately (per guild member) could help lower the level of paperwork

**Describe the solution you'd like**
The preferred solution is implementation of personal guild bank accounts. The only operations that are available per this private deposit box will be moving gold in and out. No % of money from any kind of activity will go there (it will go to general guild bank, as it is now). Keep in mind, that this feature is not suppose to be a transaction history, just one number, that represents the current amount of gold stored in account.
To avoid too much database consumption, a command may be needed to create a presonal account, so not everyone joining the guild will have one by default. Also, leaving the guild transfers all funds from personal account to the player and deletes it to free some database space.

**Describe alternatives you've considered**
The alternative solution is to create a guild bank ledger. It dont need to contain a history of operations, just the balance of each user (difference between payments and withdraws). However, this may be problematic, as the gold placed in bank by the game (guild adventures, % of guild members quests) is 'public' and not linked to specific player. So, distributing this gold between members will ultimately create a endless negative balance, with will not bring much clarity how much individual money each member has got in bank.

**Additional context**
Similar to guild bank, personal account can have few tiers of upgrading the max amount of money that can be stored.

**Comment by Gelbpunkt** [comment]
thieves are a core aspect of this game. A guild bank is a *guild* bank and not a shared place to keep money safe (at least that's how it's intended; what people make out of it is not in my hands). The aspect of it being safe from thieves is a side effect and not a main goal. I dislike making life for thieves harder, as their chances of stealing more than even $1 are less than ~5%.
