### ISSUE TITLE
Trivia

### ISSUE THREAD

**Issue by NoNameJr245** [Gelbpunkt/IdleRPG#282]
**Is your feature request related to a problem? Please describe.**
IdleRPG doesn't seem to have enough ways to make large sums of moneys... The richest gamble to the top. If the game is less dependent on gambling, this also means less gambling bots... Or gambling bots become obsolete.

**Describe the solution you'd like**
Please add trivia to the bot...
- Add a prize of crates or money. Maybe allow the user to choose which, or randomize it. **Or give crates *and* money.**  (I like this one)
- I also think that higher difficulty questions should give better prizes too... But not too much, because cheating is easy.
- And, obviously, you need a cooldown. I would say an hour.

**Describe alternatives you've considered**
No trivia... I guess. Or find another way to make large sums of money, such as strategy games with rewards. (Not gambling)

**Additional context**
I appreciate that you are trying to solve the problem of gambling being superior in money making.

**Comment by forceeeee** [comment]
I kinda like this idea but it can be abused, people can just look in the code for the answers to the questions

**Comment by maxx0911** [comment]
an easy way to fix this would be to implement a timer and get the questions and answers from a non-public api

**Comment by forceeeee** [comment]
I'd expect it to be idle related or else people can search it up

**Comment by forceeeee** [comment]
If you have 50+ wpm then you can get the answer in No time

**Comment by forceeeee** [comment]
But it has to be hard questions

**Comment by forceeeee** [comment]
But like you said, non-public source, so I guess it works

**Comment by NoNameJr245** [comment]
I doubt people are gonna be able to bot that... That's like botting a captcha, and so the amount of money you get (cheating or not cheating) is gonna still be dependent on your activity. Also an extra $1000 or a couple crates every hour aren't gonna carry you near richest. Alts are a thing tho, so I think at least most questions should not be able to Google.

**Comment by NoNameJr245** [comment]
Main point - Unless you are using alts to manually cheat, the extra money won't carry you even near richest anytime soon.

**Comment by Gelbpunkt** [comment]
I'm very sorry to say this, but Trivia can be automated, yea. The goal of Idle is that you gain money by playing; being able to get it by spamming trivia is nothing I'd like

**Comment by NoNameJr245** [comment]
It's alright... Thank you for the feedback, boss
