### ISSUE TITLE
Pet bug that doesn't update players about their pet's status

### ISSUE THREAD

**Issue by maxx0911** [Gelbpunkt/IdleRPG#285]
**Describe the bug**
Occasionally, player's pets will run away without the player being notified. This will leave their class as ranger or any of its evolutions, however they won't have access to any of the pet commands. There will simply be no reply by the bot. Cooldown for `$pet hunt` triggers.

**To Reproduce**
1. Be a ranger (the user who reported it had ranger as their secondary class)
2. Wait, you want the pet to run away, not starve.
2.5. You may need to wait more than two hours before checking your pet's status
3. Check your pet using `$pet` or any of its subcommands
4. You will not see any reply

**Expected behavior**
Either that the pet is still alive, or a status update for it, telling you that it ran away.

**Screenshots**
[A user trying to see their pet's status](https://user-images.githubusercontent.com/47576240/65386141-fa130100-dd37-11e9-8629-0158db81f0cd.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
nothing to add

**Comment by Gelbpunkt** [comment]
I've had some more debugging on this case and didn't yet manage to fix the issue as it's very very weird. Maybe I'll manage to soon

**Comment by Gelbpunkt** [comment]
Should be fixed now
