### ISSUE TITLE
Luck balance 

### ISSUE THREAD

**Issue by Tirvanel** [Gelbpunkt/IdleRPG#291]
Currently, gods are required to set luck between 0 and 2. Mathematically, this doesn't make sense, as reductions have a greater impact than increases. To have an average success chance of 1x base, the range should be .5-2, for a 1/2 and 2x minimum and maximum respectively. At low luck, players are repeatedly failing at A1, which isn't fun for anyone.

**Comment by Stevelion** [comment]
iirc, luck is additive not multiplicative (so 0 and 2 luck have equal/opposite impacts)

**Comment by Tirvanel** [comment]
Per calcchance in https://github.com/Gelbpunkt/IdleRPG/blob/v4/utils/misc.py luck appears multiplicative.

**Comment by Stevelion** [comment]
Hmm I guess you're right

**Comment by Tirvanel** [comment]
It's luck booster that's additive.

**Comment by Gelbpunkt** [comment]
Having a base chance of 100%, you'll be at 200% with 2.0 luck and at 20% with 0.2 luck. If it was 0.5-2.0, the average luck would be 125% here, which is totally unfair against atheists.

**Comment by Tirvanel** [comment]
@gelbpunkt could it be weighted so that the chances are equal above and below 1, but the range is still 1/2 to 2? Because a range of 0-2 isn't fair to followers. 200% is double the chance, but 20% is lower than a quarter the chance.

**Comment by Tirvanel** [comment]
The necessary formula would be:
if luck < 1:
    luck = (luck/2)+.5

**Comment by Stevelion** [comment]
I think the point is that since luck is multiplicative, 0.5 luck has the inverse effect of 2 luck

**Comment by Tirvanel** [comment]
Yes, that. Even though the average is 1, the impact of .5 and the impact of 1.5 aren't equivalent. 2 is the equivalent of .5.

**Comment by Tirvanel** [comment]
Basically, right now, because of the way it's set, you do better as an atheist rather than following a God who rolls randomly. (As an aside, I also think there should be some sort of bad luck prevention, but that's not for this issue.)
