### ISSUE TITLE
F in chat when raid fails

### ISSUE THREAD

**Issue by Stevelion** [Gelbpunkt/IdleRPG#292]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Make the bot react with F whenever the raid wipes/times out so people can react

**Describe alternatives you've considered**
Enable reactions in #raid-main

**Additional context**
Not exactly important/urgent lol

**Comment by forceeeee** [comment]
P E R F E C T

**Comment by NoNameJr245** [comment]
Yes. Just yes

**Comment by forceeeee** [comment]
@Gelbpunkt plx dun close dis post

**Comment by maxx0911** [comment]
#310 ¯\_(ツ)_/¯

**Comment by forceeeee** [comment]
Yay
