### ISSUE TITLE
Last resort bank

### ISSUE THREAD

**Issue by forceeeee** [Gelbpunkt/IdleRPG#294]
**Is your feature request related to a problem? Please describe.**
Sometimes people might want to transfer items to other accounts or they might be going over seas and they are worried they might lose their account/character

**Describe the solution you'd like**
Add a bank that can be accessible by any player that knows its password, so it can be accessible by multiple accounts and if you lose your account you can still get your items.

**Describe alternatives you've considered**
It would be something like $bank create > $Bank add [password] , it is now accessible by any player by doing $bank [password]

**Additional context**
Just make sure you do the password in your dms also these are example commands: $bank [password] add item [ID]

E.G `$bank 20ejdhuwaocm82 add item 8029382`
       `$bank 20ejdhuwaocm82 add money 500000`
        `$bank 20ejdhuwaocm82` will show you your items in the bank
        `$bank 20ejdhuwaocm82 add crates rare 15`

**Comment by forceeeee** [comment]
~~I would like this update to be done today because I'm going for a month~~

**Comment by numbermaniac** [comment]
This kind of sounds like a guild bank but you can deposit anything in it. Either way that's a big ask to be completed in a single day.

**Comment by Alpha157** [comment]
this sounds too op
what about you create it for 30k, for $100k, 20 crates and 15 items storage space
upgrades should be expensive because you can store more than money in it
idk if it's too expensive

**Comment by forceeeee** [comment]
30k is a good price to open a bank

**Comment by forceeeee** [comment]
Upgradable to 1m , 200 crates, 125 items

**Comment by forceeeee** [comment]
And I was in a rush at the time lol, 1 day is too little, but I would like it implemented within the next 3 months

**Comment by Gelbpunkt** [comment]
This is not really necessary. I don't see any point in it.
