### ISSUE TITLE
Adventure Bug 

### ISSUE THREAD

**Issue by TwigsyYT** [Gelbpunkt/IdleRPG#295]
**Describe the bug**
I was in contact with aspire just now. We believe that there is a bug with my game atm. My character is level 10 and has 30+ atk and def, but it says i have a less then 36 chance to complete adventure 1 and a -2 chance of completing adventure 10. I've had this issue for the past day or 2. I sent my hero on 2 level 4 adventures and both failed back to back. I was hoping you could try to solve this.
**To Reproduce**
1. Do '$adventures'

**Expected behavior**
Have a higher chance of success with the stats my character has.

**Screenshots**
https://media.discordapp.net/attachments/626251049992192011/626253294049951744/unknown.png
https://media.discordapp.net/attachments/626251049992192011/626253230120108062/unknown.png
https://media.discordapp.net/attachments/626251049992192011/626253108434960385/unknown.png
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser n/a
 - Version n/a

**Comment by Stevelion** [comment]
Likely due to low luck, check with $luck

**Comment by Gelbpunkt** [comment]
Seems a luck thing and not a bug
