### ISSUE TITLE
$i (minstat) (maxstat)

### ISSUE THREAD

**Issue by Alpha157** [Gelbpunkt/IdleRPG#297]
Some people have a lot of items, and if they want to find an item of a certain stat it will take a long time to scroll through it. 

Examples - 
$i 20 21 : will show stats from 20 to 21 
$i 30 30 : will show 30 stats
$i 42 51 : will show 42 - 51 stats

EDIT: to make this easier i also suggest $i (sword/sw/shield/sh) (minstat) (maxstat) 
also to make people's lives easier

**Comment by Gelbpunkt** [comment]
Added by @maxx0911
