### ISSUE TITLE
Bug with Ritualists receiving less loot (not confirmed)

### ISSUE THREAD

**Issue by maxx0911** [Gelbpunkt/IdleRPG#298]
**Describe the bug**
It seems as if the Ritualist class receives less loot than not being in the Ritualist class line.
I've completed multiple adventures with the Ritualist class but haven't received any loot at all, however I recently changed back to another class and have instantly received a loot item from completing an adventure.

**To Reproduce**
1. assign the Ritualist class (I had it as the second class)
1.5. `$evolve`
2. Go on an adventure and wait for it to finish
3. Use command `$status`
4. You will not, or very rarely receive loot items.

**Expected behavior**
You should receive loot items more often with the Ritualist class than without

**Screenshots**
no applicable screenshots, however you can confirm it when using `from:Chippy#3660 $s` in the Discord searchbar in the support server and see the bots answers.

**Additional context**
It might just be ***really*** bad luck, but since this isn't the first time I've seen this, I choose not to believe that.
User Suki#0877 has experienced this too.

**Comment by Gelbpunkt** [comment]
Code is fine, check it your own: https://github.com/Gelbpunkt/IdleRPG/blob/v4/cogs/adventure/__init__.py#L432

**Comment by maxx0911** [comment]
I did actually check it several times before. I guess it's just baffling that I'm this unlucky with the class, and now without the class I already received two loot items from two adventures.
Sorry about that.
