### ISSUE TITLE
Unable to Log into IdleRPG Wiki

### ISSUE THREAD

**Issue by HazelEyed** [Gelbpunkt/IdleRPG#303]
**Describe the bug**
Trying to log into the wiki account I created for IdleRPG and getting the following error message.

**To Reproduce**
Go to: https://wiki.travitia.xyz/index.php?title=Main_Page
Select Login Link
Prompted for ID/Password
After clicking LOGIN received the following error message
[5e7cca1c770295215cdd5d4c] 2019-09-26 22:56:39: Fatal exception of type "BadMethodCallException"

**Expected behavior**
I expected to login and be able to create and edit pages as I have previously done.

**Screenshots**

*
<img width="723" alt="Screen Shot 2019-09-26 at 8 28 20 AM" src="https://user-images.githubusercontent.com/54501712/65730484-c22cf600-e076-11e9-8e5d-b97e8eea8ea9.png">

*Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version Google Chrome is up to date
Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by Gelbpunkt** [comment]
Resolved!
