### ISSUE TITLE
Guild command to remove invalid users

### ISSUE THREAD

**Issue by Stevelion** [Gelbpunkt/IdleRPG#304]
**Is your feature request related to a problem? Please describe.**
Pretty sure atm you can't kick/demote users the bot doesn't share a server with (using ID returns malformed argument)

**Describe the solution you'd like**
Bot can handle dev ID in place of username#tag

**Describe alternatives you've considered**
$guild purge or similar command that kicks all players that don't share a server with the bot

**Comment by Gelbpunkt** [comment]
It does work with user IDs the bot cannot see, the code is made for that.
