### ISSUE TITLE
confirmation message when ``$follow``ing a god

### ISSUE THREAD

**Issue by shintarowo** [Gelbpunkt/IdleRPG#311]
**Is your feature request related to a problem? Please describe.**
yes, users have complained about negative luck having a huge impact on adventure success chance compared to positive luck so I propose this change based on ``dtfe#0001`` feature request. He suggests that there be some kind of confirmation message prompted to an user when they click the reaction that leads them to follow a deity. 

**Describe the solution you'd like**
add a confirmation to the ``$follow`` command, prompt it when the "follow" reaction is clicked.
ex - "Warning: Gods/Goddesses are able to alter your luck that impacts your adventure success chances. Are you sure you want to follow (God/Goddess name)?"
something along the lines of ^^

**Describe alternatives you've considered**
 allow users that desire to be an Athiest to have a one time permission to unfollow a god and not be able to follow another one.

**Additional context**

**Comment by shintarowo** [comment]
additional info: I personally see this as an issue because most players aren't even aware of the luck effects and they are told after they've already chose a god resulting them to deleting their characters. 
sure, you may transfer your money, items and guild ownership to your alt, but your character level does affects your adv chance as well as all the progress you've made throughout your whole experience playing IdleRPG.

**Comment by Gelbpunkt** [comment]
Added in v4.1.6
