### ISSUE TITLE
Longer guild adventure signup

### ISSUE THREAD

**Issue by Stevelion** [Gelbpunkt/IdleRPG#312]
**Is your feature request related to a problem? Please describe.**
It's really easy to miss signup for guild adventures even with @everyone pings with only 1 minute to sign up

**Describe the solution you'd like**
Longer minute signup time (ie 5 minutes)

**Comment by NoNameJr245** [comment]
agreed

**Comment by Gelbpunkt** [comment]
Added, but not applied. Will restart the bot this afternoon into v4.1.6 and it'll be 5min.
