### ISSUE TITLE
Marriage to more than one user.

### ISSUE THREAD

**Issue by teslaeffects** [Gelbpunkt/IdleRPG#320]
Being inclusive to people who are polyamorous, please give to option to have more than one married partner.

**Comment by numbermaniac** [comment]
Welcome to 2019, folks

**Comment by maxx0911** [comment]
While I do like the idea of Polyamory, I don't think it's worth the effort, changing the whole database with altering everyone's partner.

Another aspect is, with multiple partners, you would get even more money when your partners complete adventures, this could be severely abused using alternative accounts.

If a more in-universe suits you better, this concept wasn't known in medieval times, which is where the bot takes place.

**Comment by Gelbpunkt** [comment]
I agree with @maxx0911, even though I see the point of this
