### ISSUE TITLE
Zemsu Raid Action Timer Increase and HP decrease

### ISSUE THREAD

**Issue by charlesmonroeofficial** [Gelbpunkt/IdleRPG#329]
**Is your feature request related to a problem? Please describe.**
For Gods of Salutations raid, it's almost impossible to survive... There ~~are 2~~ is 1 problem~~s~~ mainly. ~~The HP of the Boss is too high and~~ we don't have enough time to choose an action... by the time we have read the options and if we try to think it through a bit its over... It's like 10 seconds?

**Describe the solution you'd like**
The time you have to decide on an action should be at least 30 seconds. Ideally, it would take into consideration the number of participants. For example, for every 20 participants, it could get reduced by 5 seconds or something like that to avoid the raid getting excessively long. 
~~Also, I don't know if that's up to the God but HP of the boss should be lower as well.~~

**Comment by shintarowo** [comment]
as the God of Salutations, I'm able to set Cyberus's raid HP so it'll be altered considerably lower next raid.

**Comment by charlesmonroeofficial** [comment]
Fair enough. I will edit the issue then! Thanks! :)

**Comment by Gelbpunkt** [comment]
Should be 20 seconds now.
