### ISSUE TITLE
Consider allowing Swords and Shields to be $sacrificed

### ISSUE THREAD

**Issue by MMagichal** [Gelbpunkt/IdleRPG#330]
**Is your feature request related to a problem? Please describe.**
After being told from high-ranking members of the IdleRPG Discord server's #support channel that the best way to obtain $loot items is to use a time booster and run $adventure 1 repeatedly, I have found that over the course of several dozen attempts of running $adventure 1, I find very little (or none at all) $loot items.

**Describe the solution you'd like**
I would like to see implemented the ability to use $sacrifice on Sword and Shield items.

**Describe alternatives you've considered**
To reiterate my above comments, I have tried every option provided to me when I asked the IdleRPG's Discord #support channel how to gain the most $favor, and I still am unable to find $loot items at the rate other people seem to be getting them.

**Additional context**
I believe that allowing Sword and Shield items to be $sacrificed would also provide an additional incentive for people to use $vote more often, as obtaining the free crate from voting would give players another option of what to do with their crate reward.

**Comment by Gelbpunkt** [comment]
This would 1) make Ritualist weak 2) defeat the whole point of grinding adventures for the loot
