### ISSUE TITLE
New way to increase the lovescore

### ISSUE THREAD

**Issue by Hanesor** [Gelbpunkt/IdleRPG#332]
**Is your feature request related to a problem? Please describe.**
The feature is not related to any problems as i know of

**Describe the solution you'd like**
The feature im thinking of is just adding the option to have the "$fuck" command to also have the option to have "safe sex", having no chance of getting kids, but will in return give a little lovescore

**Describe alternatives you've considered**
I dont have any alternative solutions, as this was just a though that passed my mind

**Additional context**

**Comment by maxx0911** [comment]
Maybe, instead of "You were unsuccessful at making a child.", the bot could say "You had a lovely night :smirk:" and increase lovescore accordingly?

**Comment by Hanesor** [comment]
That might be a solution yeah, was just thinking of another way of increasing the love score ;)

**Comment by Gelbpunkt** [comment]
@maxx0911's idea has been implemented.
