### ISSUE TITLE
Adventure Advancements - Concept.

### ISSUE THREAD

**Issue by Idle-Solitude** [Gelbpunkt/IdleRPG#337]
**Context**
I find that Adventures are generally just an occasional action and don't offer much interaction as a whole. I do realise this is an 'IDLE' game, that being said i would like to see some additional content.

**The Concept**

After every adventure there would be a chance of a Mini Boss spawning (1/20). The boss would scale in strength depending on what Adventure it was spawned from, this would also impact the reward potential. In regards to how this would work here are a couple of options.

1. The boss is spawned for guild members to collaborate and kill. This would offer a reward of cash. The cash would be sent directly into the guild bank for the guild to distribute as it sees fit. ALSO the person who encountered the boss would receive a fixed direct payment upon finding/spawning the mini boss.

2. The player can directly interact with the mini boss and it allows the player to battle the boss in an $activebattle style format. This would provide lucrative rewards for the player. 

3. The Mini Boss is made public and anyone can attack it. Similar to raids however the person who deals the most damage will receive a reward. The boss spawn rate would have to be different so there isn't 100s of bosses spawning at the same time.

I think this would just be a nice feature to add to the Adventures. Potentially looking into adding skills/abilities which are assigned to certain roles/classes. However this is a different concept.

Regards, Solitude.

**Comment by Gelbpunkt** [comment]
Please **follow** a template
