### ISSUE TITLE
Guild Upgrading.

### ISSUE THREAD

**Issue by Midir-art** [Gelbpunkt/IdleRPG#340]
I was at my peak 15 min ago, the fact that I have to say was is the sad part. I had finally filled up my guild bank; I was so happy. I was seeing if I could enlargen my guild bank. I typed ".guild upgrade", upon doing so I lost 125k with out my permission. 
Now all of my countless hours and efforts are waisted because of this broken feature...
Please ask for confirmation first.
I'm quite sad at my pity 224 gold.
-ミディール#9320

**Comment by Gelbpunkt** [comment]
Fixed a while ago already
