### ISSUE TITLE
Default profile image text color

### ISSUE THREAD

**Issue by girthbrooks** [Gelbpunkt/IdleRPG#349]
**Is your feature request related to a problem? Please describe.**
No problem, just a suggestion.

**Describe the solution you'd like**
To change the default color of the text that the $profile command image displays to black from white.

**Describe alternatives you've considered**
I am aware of the the color command and have changed it to black.

**Additional context**
Just a suggestion to use black as the default text color as I feel its easier on the eyes to look at on that parchment color background.  I already changed mine with the color command, but I think the black would be better as the default over white.  Thanks for making a kickass bot, my friends and I are really enjoying it!

**Comment by Gelbpunkt** [comment]
Done.
