### ISSUE TITLE
Create a #suggestions channel in Discord.

### ISSUE THREAD

**Issue by charlesmonroeofficial** [Gelbpunkt/IdleRPG#352]
Not everyone who plays the game has a github account. 
Most if not all non-developer users don't even know what it is.
This should be reserved for actual issues and bug reports in my opinion.

A suggestions channel with a nice submission mechanism and a way to upvote suggestions and check the top ones (already done in my servers) would be great and I'm sure people will come up with tons of interesting ideas for the bot. 

You don't have to implement any of those of course.
Just a more efficient way of getting people excited and involved.

**Comment by Nyathaleen** [comment]
Naya agrees on adding a suggestion channel
![kyawawa](https://user-images.githubusercontent.com/34423000/66924671-557c9a00-f02b-11e9-8468-7d6d173914ea.png)

**Comment by StrathRa** [comment]
![agree](https://user-images.githubusercontent.com/56650332/66943901-13972800-f01a-11e9-9c54-60bd9f07a38c.jpg)

**Comment by Gelbpunkt** [comment]
This was a thing earlier and it just does not work out for me. I am too unorganized to use such channel and too tired to keep it empty from duplicates and spam. GitHub is easier here as it allows e.g. comments on issues or requests and I can label them easily.
Sorry
