### ISSUE TITLE
Trick or treat "steal" can steal from yourself.

### ISSUE THREAD

**Issue by KySoto** [Gelbpunkt/IdleRPG#360]
**Describe the bug**
In trick or treat, you can "steal" from yourself

**To Reproduce**
get lucky on the sql query.

**Expected behavior**
I would expect to not be the random stranger who gives myself 50 bucks

**Additional context**
its on line 88

**Comment by maxx0911** [comment]
This reminds me of #299 
Give me a second while I give that a fix too

**Comment by maxx0911** [comment]
@Gelbpunkt don't forget to close this 😄
