### ISSUE TITLE
Cooldowns on failures (even by others)

### ISSUE THREAD

**Issue by FatherAdam** [Gelbpunkt/IdleRPG#362]
When another player uses a command without the proper perms (especially guild commands), it shouldn't issue a cooldown.
 Picture attached.

Should also do the same for other commands and have a safety net if typoes are made and the command doesn't do the intended function.
![Screenshot_20191018-151048_Discord](https://user-images.githubusercontent.com/56739946/67122025-e0d86580-f1ba-11e9-8a42-c002cf61817c.jpg)

**Comment by Gelbpunkt** [comment]
Duplicate
