### ISSUE TITLE
Adding Bank / Storage

### ISSUE THREAD

**Issue by burishak** [Gelbpunkt/IdleRPG#373]
**Is your feature request related to a problem? Please describe.**
Many player create a second account just only to store their money,afraid to get stolen by thief and thats very ineffective and complicated

**Describe the solution you'd like**
I would suggest for adding a Bank / Storage (which the developer prefer for the naming) which is same purpose that the player could Deposit their money and Withdraw it with their liking

**Describe alternatives you've considered**
Tracking the balance everytime the player completed the Adventure / Raid / Gambling, so not spamming $e / $economy all the time

**Additional context**
I hope you would consider this request for the better economy system

**Comment by Gelbpunkt** [comment]
There is a guild bank already which can be used to hold your money. More alts won't really help the cause
