### ISSUE TITLE
Prevent selfbots

### ISSUE THREAD

**Issue by Gelbpunkt** [Gelbpunkt/IdleRPG#6]
Note to self:
Idea is a captcha if people use commands too often.
Idea:
If someone uses the same command 25 times in a row (or period of time?) they have to complete a captcha to verify they're not selfbotting.
This would be an image with a text to type. If they fail or do not recognize it, they get banned from the bot temporarily and reported to staff.

**ToDo!!!**

**Comment by JaonHax** [comment]
Maybe have the captchas stored elsewhere, on-server or something, not in the GitHub, otherwise someone could potentially make the self-bot bypass the captchas after identifying which number captcha it is, either by image name or image recognition.

**Comment by Gelbpunkt** [comment]
Keeping this as a ToDo, rather hard to find time to write a captcha generator right now

**Comment by Gelbpunkt** [comment]
Will use node-canvas and a webserver in express to seperate this out. Progress should follow soon

**Comment by Gelbpunkt** [comment]
Progress update - I managed to create a basic API for making simple captchas. It works fine and will be included in a future update

**Comment by Gelbpunkt** [comment]
An implementation is there in v4. It may be altered to different behaviour, but I'm closing this for now because the idea is fulfilled
