### ISSUE TITLE
Bot adds itself to guild adventure, and won't let anyone else in

### ISSUE THREAD

**Issue by numbermaniac** [Gelbpunkt/IdleRPG#61]
Screenshot:
![Screen Shot 2019-05-19 at 11 40 58 am](https://user-images.githubusercontent.com/5206120/57976755-0524f000-7a2b-11e9-8224-499c13ab360a.png)

IdleRPG's own reaction seems to be causing the bot to join the guild adventure. Some users in the #bug-discussion channel seem to be saying that it won't let anyone else in when they try it.

**Comment by Gelbpunkt** [comment]
https://github.com/Gelbpunkt/IdleRPG/blob/v3.5/cogs/guild.py#L715
This seems impossible? O.o

**Comment by Gelbpunkt** [comment]
Weird one - seems the first person gets added, but then noone can anymore

**Comment by Gelbpunkt** [comment]
The last time I tried it now, it seems to work. Does it for you?

**Comment by numbermaniac** [comment]
Yeah I thought it was odd too because I couldn't find any reason in the code for why it would happen. Just tried it again myself and it's not adding itself anymore, so I guess we'll say it's fixed.

Perhaps the VPS was running an old version of the code before?

**Comment by Gelbpunkt** [comment]
Indeed, it was. :D
