### ISSUE TITLE
Blackjack double-down doesn't check if you have enough money

### ISSUE THREAD

**Issue by numbermaniac** [Gelbpunkt/IdleRPG#64]
Seeing a few reports of this in the feedback channel. Double-down in blackjack doesn't check if you have enough money first.

![](https://cdn.discordapp.com/attachments/562406459652964354/580447479024320550/Screenshot_2019-05-21_at_18.30.04.png)

Reproduced it myself by having $1, betting it on blackjack and then doubling down:
![Screen Shot 2019-05-22 at 12 48 57 pm](https://user-images.githubusercontent.com/5206120/58143979-0acf3f80-7c90-11e9-9fe8-5c207480f82c.png)

**Comment by Gelbpunkt** [comment]
Fixed
