### ISSUE TITLE
Possible overwriting issue in activeadventure

### ISSUE THREAD

**Issue by numbermaniac** [Gelbpunkt/IdleRPG#72]
https://github.com/Gelbpunkt/IdleRPG/blob/v3.6/cogs/adventure.py#L143

Now that `_` is being used as a function for translation, is having underscore here overwriting that and causing the rest of the function to break?

Active adventures are currently broken - not sure if maybe this line is the cause?
![Screen Shot 2019-05-29 at 11 49 06 pm](https://user-images.githubusercontent.com/5206120/58562339-6723f780-826c-11e9-8a18-dcd8ade2f982.png)

**Comment by Gelbpunkt** [comment]
The error here says that `_()` is undefined in the docstring, but it is defined everywhere else in the file... no clue. I'll however change that line just in case

**Comment by Gelbpunkt** [comment]
Oh well, it fixed the command. Thanks a lot for the tip!
