### ISSUE TITLE
Problem with equipment value that causes it cannot freely transact on the market 

### ISSUE THREAD

**Issue by xyndrome01** [Gelbpunkt/IdleRPG#76]
![Screenshot_20190629-231907](https://user-images.githubusercontent.com/52354312/60386388-ca50b600-9ac6-11e9-89f2-48b0402f231a.png)

I hope all of equip have value more than 70,
Or the selling system can change from 1000x value to 10000x value
So players can freely throw price in market
Especially for equipment with stat more than 25

![Screenshot_20190628-190926](https://user-images.githubusercontent.com/52354312/60386533-95456300-9ac8-11e9-8cef-d5c6155076e6.png)

I hope you can consider this problem. 
Thanks

**Comment by HaaLife** [comment]
I think its the purpose of item values. So item prices are not just based from stats.

**Comment by Gelbpunkt** [comment]
@HaaLife is correct. As I want to limit the market prices, but not set the limits stat-wise, values seem the logical way. x10000 seems really bad in my view, as items have values up to ~1k, which results in prices up to 10,000,000, which is silly to me
