### ISSUE TITLE
bot only play first song we add 

### ISSUE THREAD

**Issue by Quinemaniac** [Gelbpunkt/IdleRPG#77]
**Describe the bug**

**To Reproduce**
1. Do '....'
2. Enter command '....'
3. Hit reaction '....'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Gelbpunkt** [comment]
Please fill out the fields and resubmit the issue

**Comment by Quinemaniac** [comment]
Dear super ultra onii-chan adrian
it wont play anysong in the queue except first song : (
