### ISSUE TITLE
Lovescore improvement

### ISSUE THREAD

**Issue by BigBepisBenis** [Gelbpunkt/IdleRPG#81]
Hello 

Currently I there is no use for the lovescore.
I was thinking it was a shame and that there was improvement to make.
If the love score effected the money you would get from your partners adventures that would be very useful and fun.
It’s also logical because the more you love someone the more you would want to spend money on them.
Thanks 
~Big_Bepis_Benis

**Comment by Gelbpunkt** [comment]
I have planned such thing in v4 by making it increase the amount of kids a couple can have. This is a useful addition.

**Comment by maxx0911** [comment]
Adding to this, not sure if this is also part of your v4 plan, but how about lovescore milestones, similar to the level up rewards? For example: You and your partner's combined lovescore reaches 10.000, so you get a special weapon, maybe Cupid's Bow; Money, Exp or crates could also be valid milestone rewards.

**Comment by HaaLife** [comment]
Maybe lovescores can affect $child cooldown too

**Comment by Defenestrate-flof** [comment]
The milestones idea sounds good. If we can get more kids slots from the milestone would be great too.

**Comment by AutobotJazzy** [comment]
Yeah everyone on the server I play on can't see any benefit from the lovescore currently so ANY addition to it that benefits from the love score would be excellent

**Comment by Gelbpunkt** [comment]
I am personally against milestones, because it would be a kind of "buying" yourself them.

What I've added now:
    - For every 250,000 Lovescore *together*, you may have one more child
    - For every 1,000,000 Lovescore of your spouse, they get 100% more money from your adventures (and for 500,000 50% more etc)

**Comment by Gelbpunkt** [comment]
I'm leaving this issue open in case anyone has ideas what kids could do. More money by having more kids sounds kinda lame to me
