### ISSUE TITLE
ActiveAdventure bug

### ISSUE THREAD

**Issue by RemnVersepallis** [Gelbpunkt/IdleRPG#83]
**Describe the bug**
This has happened twice , i use the command ActiveAdventure and around 70+% of finishing the adventure it freezes and wont continue. i press every button hoping it would unfreeze and then it times out . First time it happened  i had maximized the window. second time it happened i had gotten some notifications. This was on PC discord. 

**To Reproduce**
1. Do '....'
2. Enter command '....'
3. Hit reaction '....'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
It might be on my end since i have no one else reporting this bug to me on the discord channel i am in . And no one else i spoke with has had this problem.

**Comment by Gelbpunkt** [comment]
It can only be your end not transmitting the reaction to Discord and/or being rate limited by Discord at the same time.
I'm closing this as it's nothing that we can fix
