### ISSUE TITLE
Beta: Captchas can be impossible if they start with the @ symbol

### ISSUE THREAD

**Issue by numbermaniac** [Gelbpunkt/IdleRPG#84]
**Describe the bug**
If a captcha starts with `@`, I can't type it on Discord on computer because it ends up pinging someone instead.

**To Reproduce**
Get a captcha that starts with `@`

**Expected behavior**
I should be able to type any captcha correctly.

**Screenshots**
![Screen Shot 2019-07-11 at 3 58 05 pm](https://user-images.githubusercontent.com/5206120/61025653-b5dcb980-a3f4-11e9-894a-2702b0daae87.png)
![Screen Shot 2019-07-11 at 3 56 26 pm](https://user-images.githubusercontent.com/5206120/61025573-89c13880-a3f4-11e9-9195-520d023417cf.png)

**Desktop (please complete the following information):**
Discord on macOS 10.14.4

**Additional context**
Some mobile users were able to send the same text without a ping. Basically, it's very inconsistent depending on where you're using Discord.

**Comment by Gelbpunkt** [comment]
I'm sorry for this one. As were switching to emoji captchas, this will hopefully no longer be a problem

**Comment by Gelbpunkt** [comment]
Fixed as it's now an emoji captcha
