### ISSUE TITLE
Beta: color

### ISSUE THREAD

**Issue by idle-Mercy** [Gelbpunkt/IdleRPG#85]
**Describe the bug**
Right now, if you change your color to anything in beta, it sets the color to black. It wouldn't be bad if I could change it back to white, but black writing trying to be displayed on the default black overlays pose an issue. Can't see the name, can't see who you're married to, or what guild you're in when you do beta profile
**To Reproduce**
1. Do beta color #f4afb4 (any color)
2. Do beta p
3. Color is black
4. try to change it back to white
5. do beta color #ffffff
6. do beta p
7. color is still black. it's stuck, rip

**Expected behavior**
Expected behavior is for it to be the color chosen in color picker. 

**Screenshots**

![](https://cdn.discordapp.com/attachments/588673604686708746/598862839410720809/Screenshot_20190711-090628_Discord.jpg)

![](https://cdn.discordapp.com/attachments/588673604686708746/598863141937479705/Screenshot_20190711-090809_Discord.jpg)

**Desktop (please complete the following information):**
 desktop discord 

**Additional context**
beta

**Comment by Gelbpunkt** [comment]
Just tested this today, cannot reproduce

**Comment by idle-Mercy** [comment]
you did beta p after? not $p? Looks like you may have done $p and pulled up the wrong one. 


![](https://cdn.discordapp.com/attachments/588673604686708746/599235992477630532/Screenshot_20190712-094935_Discord.jpg)

**Comment by numbermaniac** [comment]
Can reproduce.
![Screen Shot 2019-07-13 at 12 00 05 am](https://user-images.githubusercontent.com/5206120/61133682-430d3480-a501-11e9-9916-d3d9676ab5fe.png)
![Screen Shot 2019-07-13 at 12 01 04 am](https://user-images.githubusercontent.com/5206120/61133714-54eed780-a501-11e9-9d22-c41be74bffca.png)

**Comment by Gelbpunkt** [comment]
Hmm that's very weird indeed. The code in beta and main bot is the same

**Comment by izzis** [comment]
maybe because command without # once?

**Comment by Gelbpunkt** [comment]
Fixed, I was always stripping the `#` off
