### ISSUE TITLE
Beta: Captcha

### ISSUE THREAD

**Issue by idle-Mercy** [Gelbpunkt/IdleRPG#86]
**Describe the bug**
If your chat is active and a lot of people are doing commands, I'm scared something like this will happen, but worse. 

![](https://cdn.discordapp.com/attachments/592794930066358284/598746699925553160/Screenshot_20190711-012341_Discord.jpg)
The one for soul and for ._. were put at the same time. This wasn't as bad as it could have been, especially when discord lags and commands send late. And if there are more people who posted at the same time, it'd be worse, they'd have to probably count up to see who did the command first and hopefully pick the right captcha, then get it right...and if they picked the wrong one, they would have to keep trying, wasting their attempts. 

**To Reproduce**
1. be in an active server
2. Enter a command that brings up a captcha while others do the same
3. if the bot is too slow, you won't know which captcha is yours. 

**Expected behavior**
I'd hope the bot would mention the person who it's intended for so that they know which captcha to do or they'll get banned for botting. 
**Screenshots**

**Comment by Gelbpunkt** [comment]
Outdated

**Comment by numbermaniac** [comment]
The bot now pings each user for the captcha message so you know who needs to complete which captcha.
