### ISSUE TITLE
Beta: Blackjack games show words instead of emojis.

### ISSUE THREAD

**Issue by idle-Mercy** [Gelbpunkt/IdleRPG#87]
**Describe the bug**
When people are playing blackjack, the code comes out weird for it, like the proper emojis aren't added, so they are betting and :aspades: comes up instead of a picture of an A of spades or :6hearts: instead of a 6 of hearts etc. 

**To Reproduce**
1. Go to play blackjack beta bj100
2. The cards come up weird

**Expected behavior**
Expected behavior is that the cards show up as emojis, not as words as shown below. 
I think maybe the bot doesn't have permission to add external emojis, or something. I can't use those emojis myself when I try, but the real bot can. So something is off on the bot's permissions and being able to add those emojis. 

**Screenshots**

![](https://cdn.discordapp.com/attachments/476780069130600448/598941377899921418/unknown.png)

**Additional context**
It is in BETA btw, this is how it looks with the real bot. I hovered over the image so the emoji code showed up.

![](https://cdn.discordapp.com/attachments/476780069130600448/598942889694724126/unknown.png)

**Comment by Gelbpunkt** [comment]
That's because the beta bot isn't in the emoji servers for the cards yet. I'll fix that tomorrow!

**Comment by Gelbpunkt** [comment]
Resolved
