### ISSUE TITLE
Beta P issues viewing SOME users' profile 

### ISSUE THREAD

**Issue by idle-Mercy** [Gelbpunkt/IdleRPG#88]
**Describe the bug**
There are some  users who I can't view their profile when doing beta p. 
When people couldn't see mine, I assumed it was an issue since I changed my background with donor...but then there's RanCh00k who isn't a donor whose background I can't view. We can view our own backgrounds by doing beta p, but they can't view ours. 
I can view some people's profiles with the beta p command, but I don't know what the common thing between those of us whose profiles can be viewed is and those whose profiles can't be viewed. it's not just me who can't see the profiles of those users, it's everyone else. Same with viewing my profile. I had people try viewing my profile and they couldn't.

Things I ruled out. They didn't delete their profile. Their profile is view-able by themselves, so it's not an issue with them using something other than the proper format to do their backgrounds (like if I try to use a gif for my background instead of jpg, it just wouldn't pull up my background in the real game)

It's not him trolling me because mine is also not able to be viewed by others, not as beta p nor as beta pp. 

It's not a HUGE issue, but I figured I'd point it out since it is in fact a bug that may not be great to have in the real game. 

**To Reproduce**
I'm not sure how to reproduce other than you trying to view the profiles of the affected people. (those in the screenshots. It's just 2 who I listed (myself and ranch00k), but there were a few more. 

**Expected behavior**
That you see the user's profile when you do beta p. 

**Screenshots**
 I'll start with the one who worked for me. 
![](https://cdn.discordapp.com/attachments/476780069130600448/599998375781335041/Screenshot_20190714-121819_Discord.jpg)

![](https://cdn.discordapp.com/attachments/476780069130600448/599998395515666434/Screenshot_20190714-121831_Discord.jpg)

![](https://cdn.discordapp.com/attachments/476780069130600448/599998402142666756/Screenshot_20190714-121842_Discord.jpg)

![](https://cdn.discordapp.com/attachments/476780069130600448/600002706102288385/Screenshot_20190714-123327_Discord.jpg)

![](https://cdn.discordapp.com/attachments/476780069130600448/600002717804527721/Screenshot_20190714-123349_Discord.jpg)

![](https://cdn.discordapp.com/attachments/476780069130600448/600002730345365504/Screenshot_20190714-123443_Discord.jpg)

**_Over here, I do it right after he does his beta p just to make sure he isn't trolling me._** 

![](https://cdn.discordapp.com/attachments/476780069130600448/600002739782549534/Screenshot_20190714-123506_Discord.jpg)

**Additional context**
Beta
It's not a detrimental issue, but one I thought would be good to bring up.

**Comment by Gelbpunkt** [comment]
@Diniboy1123 has identified the issue source and I'll resolve it asap

**Comment by Gelbpunkt** [comment]
Fixed
