### ISSUE TITLE
Tie in blackjack shouldn't it PUSH?

### ISSUE THREAD

**Issue by zeny696** [Gelbpunkt/IdleRPG#89]
**Is your feature request related to a problem? Please describe.**

It's frustrating when you play blackjack and get a TIE. It takes your money and in the Casino I just get a free play where they don't take my money and I go again.

**Describe the solution you'd like**

I'd like to get Casino rules where you lose no money and you go again,

**Describe alternatives you've considered**

Change TIE to PUSH like in the Casino.

**Additional context**

None

**Comment by AutobotJazzy** [comment]
Yes this drives me bonkers too!

**Comment by Gelbpunkt** [comment]
Fixed
