### ISSUE TITLE
Market display breaks due to backtick in username

### ISSUE THREAD

**Issue by numbermaniac** [Gelbpunkt/IdleRPG#9]
Screenshot:
![screen shot 2019-02-01 at 4 38 34 pm](https://user-images.githubusercontent.com/5206120/52104717-fcf1a200-263f-11e9-8f05-adade6e8caf5.png)

It's only happening for this specific item. I'm guessing maybe the user has a backtick in their username, so all the `code fragments` are now being mismatched?

**Comment by Gelbpunkt** [comment]
The user's exact name is `🍷 _;(´ཀ`」∠);_...`.
I can't see how that would affect the markdown, though. Only the `_` would cause something to break, but definitely not the newlines to be gone. No clue

**Comment by Gelbpunkt** [comment]
Maybe escaping user names would help here

**Comment by numbermaniac** [comment]
I just tested, and if you type:
![screen shot 2019-02-01 at 6 48 38 pm](https://user-images.githubusercontent.com/5206120/52109602-2ddad280-2652-11e9-8c07-77a9b2b70863.png)
It turns into:
![screen shot 2019-02-01 at 6 49 17 pm](https://user-images.githubusercontent.com/5206120/52109610-316e5980-2652-11e9-97cc-7cb039b870fa.png)

However, put a space between those two backticks:
![screen shot 2019-02-01 at 6 49 24 pm](https://user-images.githubusercontent.com/5206120/52109615-37fcd100-2652-11e9-8ac7-21955b13c151.png)
And suddenly Discord removes the new line:
![screen shot 2019-02-01 at 6 49 30 pm](https://user-images.githubusercontent.com/5206120/52109626-43e89300-2652-11e9-83ec-72b0fab8d003.png)

**Comment by Gelbpunkt** [comment]
Fixed! Thanks to @Jashanlol
