### ISSUE TITLE
Change the $create error response 

### ISSUE THREAD

**Issue by Defenestrate-flof** [Gelbpunkt/IdleRPG#90]
**Is your feature request related to a problem? Please describe.**
The description: “You don’t have the permissions to use this command. Is it thought for other users.” makes a lot of newer players confused. We got questions about this at least 2 times per week.

**Describe the solution you'd like**
Change the description into "You already have a character. Use `$profile`  to see your profile." 

**Describe alternatives you've considered**
I haven't thought of another alternative. But I do think bot banned players should see the original response instead of this one above.

**Additional context**
Screenshots of the latest questions about the issue.
https://imgur.com/pHjWIwH

**Comment by Gelbpunkt** [comment]
Changed by @numbermaniac

**Comment by numbermaniac** [comment]
Wait...did I? #100 changed the `$delete` confirmation, not the `$create` error message.

**Comment by Gelbpunkt** [comment]
Oooooops

**Comment by Gelbpunkt** [comment]
I'll fix this in v4 when I'm back from holidays

**Comment by Gelbpunkt** [comment]
Added in v4
