### ISSUE TITLE
Beta: Captcha 2.0

### ISSUE THREAD

**Issue by idle-Mercy** [Gelbpunkt/IdleRPG#91]
**Describe the bug**
Sometimes the emojis we have to pick don't show up and we get banned because it takes more than 15 seconds for them to show up... 

**To Reproduce**
well, it's random really. I had great internet (150/150 which was probably 120/100) and it still happened to me. Discord gets laggy at times because it's discord. 

**Expected behavior**
When you do the captcha, all of the options show up, including the correct one. 
Maybe if you give more time, and do the captcha as discord emojis so we can search them up if they don't show up and put them in ourselves it may work out...but we'll need more time to search for them...at least a minute if not more. I mean...15 seconds is nothing, especially with a not so good connection. 

**Screenshots**

![](https://cdn.discordapp.com/attachments/592794930066358284/601222767949512711/Screenshot_20190717-212107_Discord.jpg)

**Additional context**
If people get banned left and right for not even being a bot, but for their internet, or discord being buggy, they aren't going to want to play. Who wants to play a game that bans them for reasons outside of their control? I've seen quite a few people have their options not show up. It takes a few days to get unbanned too, so it's not even a light thing, like run on over to the support server and tell them in support about the issue and you're unbanned. You may wait a few days, you may wait longer. I'm on day 2, some are on day 3 or 4 (they say) After a few days, people start losing interest and move on. It's beta, so I have the real game to fall back on, but discord isn't super reliable when it comes to lag, so maybe don't give such harsh time limits. I've seen the bot be unable to do/finish a raid because of discord lagging, so why only 15 seconds? When it didn't show up, I tried to search for the emoji, but I didn't find it in time...and there are 2 dragons, neither looked like the one that showed up.

**Comment by Gelbpunkt** [comment]
I surely understand that it's frustrating to attempt to play the bot and in the end getting banned because it's not on your end.

However, you already hit the nail on the top: Here, the bot is not the issue, as it only calls the Discord API, but Discord returns a success. That means it thinks the reaction is added, because Discord says so. But Discord doesn't add the reaction - or, it doesn't send the reaction over the WS.

I don't know a fix nor an alternative here

**Comment by pphe** [comment]
Would having a reaction to generate a new (one-time) captcha work in this case? And extending the timer to at least 30 seconds.

**Comment by kaleb604** [comment]
A suggestion for a possible fix to this is adding a slight delay between each emoji add. When I was do a little bit in Discord.js a slight wait limited the amount of times an emoji didn't show up (I believe I still have the code for example if you want)

**Comment by kaleb604** [comment]
Looking at what I did in Discord.JS, I used the async & await functionality and never had an issue with it. Once again my bot was a lot smaller, but that may be a step in the right direction. Hope it helps

**Comment by Gelbpunkt** [comment]
IdleRPG is asynchronous

**Comment by Gelbpunkt** [comment]
Closing as captchas are now no longer planned
