### ISSUE TITLE
Merch multiple items

### ISSUE THREAD

**Issue by moraug** [Gelbpunkt/IdleRPG#92]
$merch id1 id2 id3 id4 - that would really help when I need to merch some items, but can't use merchall. Or maybe a new command with a cooldown like merchall

**Comment by AutobotJazzy** [comment]
I have been wanting this for weeks myself. I see people going through pages of their items daily and they purge item after item but not all of them and it really messes up the flow of some games or conversations having to wait for them to get done.

**Comment by Gelbpunkt** [comment]
Added in v4
