### ISSUE TITLE
Purchase all

### ISSUE THREAD

**Issue by kaleb604** [Gelbpunkt/IdleRPG#93]
**Is your feature request related to a problem? Please describe.**
It's annoying to have to purchase each booster separately. 
**Describe the solution you'd like**
(Prefix: $) 
*$Purchase all* should allow you to purchase one of all boosters
**Describe alternatives you've considered**
$purchaseall
**Additional context**

**Comment by AutobotJazzy** [comment]
I agree with this. Purchasing should be easier I think. Either purchase all for 1 of each or add an additional command line for quantity so if you want 4 luck boosters you should be able to do something like $purchase 4 luck

**Comment by Gelbpunkt** [comment]
Just a heads up: you can already buy multiple of the same type with `$purchase time 100`

**Comment by Gelbpunkt** [comment]
Added v4
