### ISSUE TITLE
Problems with $offer cooldown

### ISSUE THREAD

**Issue by forceeeee** [Gelbpunkt/IdleRPG#95]
**Is your feature request related to a problem? Please describe.**
Every time I try to buy multiple items off a character, I have to wait around 2 minuets to buy
the next item due to the $offer cool down. And it is very frustrating to wait a few minutes between every purchase.

**Describe the solution you'd like**
Please remove the cooldown or at least turn it down to 20 seconds.

**Describe alternatives you've considered**
Or make it so that you can trade multiple items in one offer.

**Additional context**
For example `$offer [id1] [id2] 12500 @character`

**Comment by AutobotJazzy** [comment]
I think this would be very helpful

**Comment by Gelbpunkt** [comment]
There's one problem that arises here: With the proposed syntax, the bot cannot know what will be an item to sell and what will be the price. 

I can imagine assuming that all numbers except the last one are IDs, but I am not happy about that

**Comment by Gelbpunkt** [comment]
I'll do this as a part of the safe Transaction system

**Comment by Gelbpunkt** [comment]
For multiple items I recommend `$trade` instead since v4.
