### ISSUE TITLE
$Money top

### ISSUE THREAD

**Issue by Avinychus** [Gelbpunkt/IdleRPG#96]
Make so that players can "$Moeny top" to see who have the most money and also "$Money top server" to see who have the most money in the server :3

**Comment by shintarowo** [comment]
you can already see the top players who have the most money by ``$richest``

**Comment by Gelbpunkt** [comment]
Server-based highscore lists are almost impossible to add with the current setup. As an alternative, there's also `$guild richest`, as I assume your mates and you will share a guild.

Closing this
