### ISSUE TITLE
Blackjack: Change how Aces are calculated

### ISSUE THREAD

**Issue by tjadenhom** [Gelbpunkt/IdleRPG#97]
**Describe the bug**

When dealt a pair of Aces at the start of a round, the total is calculated as 22 resulting in automatic loss.

**To Reproduce**
1. Do '....'
2. Enter command '....'
3. Hit reaction '....'

Being that it's random dealing, you just hope for getting dealt 2 Aces in your initial hand.

**Expected behavior**

In blackjack, Aces can either be 1 or 11. In the case of 2 Aces, the total is typically either 2 or 12.

**Screenshots**

![double_aces_bug](https://user-images.githubusercontent.com/27646696/61807862-f4fd0880-adff-11e9-9e3f-dab6fa481d6d.JPG)

**Additional context**

A minor and rare occurrence, I'm sure, but an important one when it does happen.

**Comment by Gelbpunkt** [comment]
I should've fixed this on the beta for the next major release. Thanks!

**Comment by Gelbpunkt** [comment]
Added in v4
