### ISSUE TITLE
SUGGESTION: Guild Adventure Pings

### ISSUE THREAD

**Issue by AutobotJazzy** [Gelbpunkt/IdleRPG#98]
**Is your feature request related to a problem? Please describe.**
Not particularly

**Describe the solution you'd like**
If you are in a guild and we are going to do a guild adventure, it would be nice if we could ping everyone in the guild to let them know we are starting one instead of pinging everyone individually

**Describe alternatives you've considered**
We have copied and pasted from the guild list but some people have hard names or special characters that don't get pinged properly depending on the device we use

**Additional context**
Our guild officer says he is usually on his phone and can't ping anyone with special characters in their name so it would be easier and more convenient to have the option to ping your guild as a whole

**Comment by idle-Mercy** [comment]
I like this idea! It's not spammy since the guild adventures happen so infrequently, mostly not even 2 in a day. I hope this gets added as an idea!!!

**Comment by Gelbpunkt** [comment]
Not everyone may want to be pinged, but the idea in general looks okay to me. Probably a way to opt-in would be ideal?

**Comment by AutobotJazzy** [comment]
Yeah the option to opt in would be great since I know not everyone likes being pinged but it seems my guild in particular always wants to be a part of the adventures and our officer can't ping everyone so they come on later griping about why they weren't pinged. I know we can ask for pings to certain channels or updates and the option to opt out of the "e" ping is there so making that work for guilds would be pretty nice.

**Comment by Gelbpunkt** [comment]
To be honest, opting-in is a big effort and guild adventure pings are hard, too.
What if not everyone is in the server?

My suggestion: Make a role for your guild members and make it mentionable, just mention them your own when you start one
